// Copyright (C) 2022-2024 Exaloop Inc. <https://exaloop.io>

#include "attr.h"

namespace codon::ast {

// const std::string Attr::Module = "module";
// const std::string Attr::ParentClass = "parentClass";
// const std::string Attr::Bindings = "bindings";

// const std::string Attr::LLVM = "llvm";
// const std::string Attr::Python = "python";
// const std::string Attr::Atomic = "atomic";
// const std::string Attr::Property = "property";
// const std::string Attr::StaticMethod = "staticmethod";
// const std::string Attr::Attribute = "__attribute__";
// const std::string Attr::C = "C";

// const std::string Attr::Internal = "__internal__";
// const std::string Attr::HiddenFromUser = "__hidden__";
// const std::string Attr::ForceRealize = "__force__";
// const std::string Attr::ParentCallExpr = "parentCallExpr";
// const std::string Attr::TupleCall = "tupleFn";
// const std::string Attr::Validated = "validated";
// const std::string Attr::AutoGenerated = "autogenerated";

// const std::string Attr::CVarArg = ".__vararg__";
// const std::string Attr::Method = ".__method__";
// const std::string Attr::Capture = ".__capture__";
// const std::string Attr::HasSelf = ".__hasself__";
// const std::string Attr::IsGenerator = ".__generator__";

// const std::string Attr::Extend = "extend";
// const std::string Attr::Tuple = "tuple";
// const std::string Attr::ClassDeduce = "deduce";
// const std::string Attr::ClassNoTuple = "__notuple__";

} // namespace codon::ast
