// Copyright (C) 2022-2024 Exaloop Inc. <https://exaloop.io>

#pragma once

#include <string>

namespace codon::ast {

const int INDENT_SIZE = 2;

struct Attr {
  enum {
    Module = 201,
    ParentClass,
    Bindings,
    LLVM,
    Python,
    Atomic,
    Property,
    StaticMethod,
    Attribute,
    C,
    Internal,
    HiddenFromUser,
    ForceRealize,
    RealizeWithoutSelf,
    ParentCallExpr,
    TupleCall,
    Validated,
    AutoGenerated,
    CVarArg,
    Method,
    Capture,
    HasSelf,
    IsGenerator,
    Extend,
    Tuple,
    ClassDeduce,
    ClassNoTuple,
    Test,
    Overload,
    Export,
    Inline,
    NoArgReorder,
    FunctionAttributes,

    ClassMagic,
    ExprSequenceItem,
    ExprStarSequenceItem,
    ExprList,
    ExprSet,
    ExprDict,
    ExprPartial,
    ExprDominated,
    ExprStarArgument,
    ExprKwStarArgument,
    ExprOrderedCall,
    ExprExternVar,
    ExprDominatedUndefCheck,
    ExprDominatedUsed,
    ExprTime,
    ExprDoNotRealize,
    ExprNoSpecial,
  };
};
} // namespace codon::ast
