# Copyright (C) 2022-2026 Exaloop Inc. <https://exaloop.io>

from __future__ import annotations

from typing import TYPE_CHECKING

from ....bridge import List, Tuple
from ... import ast, cache
from . import call, function, infer, utils
from .ctx import Item, TypecheckError

if TYPE_CHECKING:
    from . import TypeVisitor


def typecheck_id(self: TypeVisitor, node: ast.IdExpr) -> ast.Node:
    """
    Typecheck identifiers.
    If an identifier is a static variable, evaluate it and replace it with its value
    (e.g., change `N` to `IntExpr(16)`).
    If the identifier of a generic is fully qualified, use its qualified name
    (e.g., replace `Ptr` with `Ptr[byte]`).
    """

    value = self.ctx.find(node.value, self.ctx.time)
    if not value:
        raise TypecheckError(node, f"name '{node.value}' is not defined")

    # If this is an overload, use the dispatch function
    if utils.is_unbound(node) and utils.has_overloads(self.ctx, value.canonical_name):
        dispatch = get_dispatch(self, value.canonical_name)
        value = self.ctx.find(dispatch.get_func_name())

    # If we are accessing an outside variable, capture it or raise an error
    check_capture(self, value)

    # Replace the variable with its canonical name
    node.value = value.canonical_name

    # Set up type
    infer.unify(node.type, utils.instantiate_type(self.ctx, value.type))
    if fn_type := node.type.get_func():
        # resolve overloads
        node.value = fn_type.get_func_name()
    if node.type.is_type(ast.types.Stdlib.Capsule) and not node.has(ast.Attr.AutoGenerated):
        node.set(ast.Attr.AutoGenerated)
        result = ast.CallExpr(
            ast.IdExpr(ast.types.mangle(cls="Capsule", func="_get")), items=[node]
        )
        return self.visit(result)

    # Realize a type or a function if possible and replace the identifier with
    # a qualified identifier or a static expression (e.g., `foo` -> `foo[int]`)
    if node.type.can_realize():
        if static := node.type.get_static():
            return self.visit(static.get_static_expr())
        if not value.is_var():
            if not (node.has(ast.Attr.ExprDoNotRealize) and node.type.get_func()):
                if realized := infer.realize(node.type):
                    node.value = realized.realized_name()
                    node.done = True
        else:
            infer.realize(node.type)
            node.done = True

    # If this identifier needs __used__ checks (see @c ScopeVisitor), add them
    if not node.has(ast.Attr.ExprNoUndefCheck):
        control_var = f"{value.canonical_name}{cache.VAR_USED_SUFFIX}"
        if self.ctx.find(control_var, self.ctx.time):
            check_stmt = ast.ExprStmt(
                ast.CallExpr(
                    ast.DotExpr(ast.IdExpr("__internal__"), member="undef"),
                    items=[
                        ast.IdExpr(control_var),
                        ast.StringExpr(utils.get_unmangled_name(self.ctx, value.canonical_name)),
                    ],
                )
            )
            node.set(ast.Attr.ExprNoUndefCheck)
            return self.visit(ast.StmtExpr(check_stmt, expr=node))
    return node


def typecheck_dot(self: TypeVisitor, node: ast.DotExpr) -> ast.Node:
    """
    Transform a dot expression. Select the best method overload if possible.
    @example
    `obj.__class__`   -> `type(obj)`
    `cls.__name__`    -> `"class"` (same for functions)
    `obj.method`      -> `cls.method(obj, ...)` or
    `cls.method(obj)` if method has `@property` attribute
    `obj.member`      -> see @c getClassMember
    @return nullptr if no transformation was made
    """

    # Check if this is being called from CallExpr (e.g., foo.bar(...))
    # and mark it as such (to inline useless partial expression)
    parent = self.ctx.get_parent_node()
    if isinstance(parent, ast.CallExpr) and not parent.has(ast.Attr.ParentCallExpr):
        parent = None

    # Flatten imports:
    # `a.b.c`      -> canonical name of `c` in `a.b` if `a.b` is an import
    # `a.B.c`      -> canonical name of `c` in class `a.B`
    # `python.foo` -> internal.python._get_identifier("foo")
    chain = []
    head = node
    while isinstance(head, ast.DotExpr):
        chain.append(head.member)
        head = head.expr
    final = node
    if isinstance(head, ast.IdExpr):
        # Case: a.bar.baz
        chain.append(head.value)
        chain.reverse()
        position, value = get_import(self, chain)
        if value is None:
            # Python capture
            base = self.ctx.get_base()
            assert base and base.py_captures is not None, "unexpected py capture"
            base.py_captures.add(chain[0])
            final = ast.IndexExpr(ast.IdExpr("__pyenv__"), index=ast.StringExpr(chain[0]))
        elif value.module_name == "std.python" and self.ctx.get_module() != value.module_name:
            # Import from python (e.g., pyobj.foo)
            final = ast.CallExpr(
                ast.DotExpr(
                    ast.DotExpr(ast.IdExpr("internal"), member="python"), member="_get_identifier"
                ),
                items=[ast.StringExpr(chain[position])],
            )
            final = self.visit(final)
            position += 1
        elif value.module_name == self.ctx.get_module() and position == 1:
            final = self.visit(ast.IdExpr(chain[0]), type_allowed=True)
        else:
            final = ast.IdExpr(value.canonical_name)
        while position < len(chain):
            final = ast.DotExpr(final, member=chain[position])
            position += 1
    if isinstance(final, ast.DotExpr):
        node.expr = final.expr
        node.member = final.member
    else:
        return self.visit(final)

    # Special case: obj.__class__
    if node.member == "__class__":
        # TODO: prevent cls.__class__ and type(cls)
        return self.visit(ast.CallExpr(ast.IdExpr(ast.types.Stdlib.Type), items=[node.expr]))

    node.expr = self.visit(node.expr)
    new_expr, found = access_attribute(self, node.expr, node.member, node.type, parent)
    if not found:
        raise TypecheckError(
            node,
            f"'{utils.extract_type(self.ctx, node.expr).pretty_string()}' object has no attribute "
            f"'{node.member}'",
        )
    elif new_expr:
        return new_expr
    if node.expr.done and infer.realize(node.type):
        node.done = True
    return node


def access_attribute(
    self: TypeVisitor,
    expr: ast.Expr,
    member: str,
    typ: ast.types.Type | None = None,
    parent: ast.CallExpr | None = None,
) -> Tuple[ast.Expr | None, bool]:

    has_side = utils.has_side_effect(expr)

    def wrap_side(value: ast.Expr) -> ast.Expr:
        wrapped = ast.StmtExpr(ast.ExprStmt(expr), expr=value) if has_side else value
        return self.visit(wrapped)

    extracted = utils.extract_type(self.ctx, expr)

    # Special case: fn.__name__
    # Should go before cls.__name__ to allow printing generic functions
    # NOTE: NO SIDE EFFECTS! (because of generic function support!)
    if extracted.get_func() and member == "__name__":
        return ast.StringExpr(extracted.pretty_string()), True
    if expr.type and expr.type.get_partial() and member == "__name__":
        partial = expr.type.get_partial()
        return wrap_side(ast.StringExpr(partial.pretty_string())), True

    expr_typ = utils.extract_class_type(self.ctx, expr)

    # Special case: fn.__llvm_name__ or obj.__llvm_name__
    if member == "__llvm_name__":
        if isinstance(expr.type, ast.types.Type) and infer.realize(expr.type):
            return wrap_side(ast.StringExpr(expr.type.realized_name())), True
        return None, True
    if utils.is_type_expr(expr) and member == "__generic_name__":
        # No side effects here, otherwise will not typecheck
        return (ast.StringExpr(expr_typ.name) if expr_typ else None), True

    # Special case: cls.__name__
    if utils.is_type_expr(expr) and member == "__name__":
        if infer.realize(expr.type):
            return wrap_side(
                ast.StringExpr(utils.extract_type(self.ctx, expr).pretty_string())
            ), True
        return None, True

    # Special case: cls.__mro__
    if utils.is_type_expr(expr) and member == "__mro__":
        if infer.realize(expr.type):
            items = [ast.IdExpr(base.realized_name()) for base in call.get_mro(self, expr_typ)]
            return wrap_side(ast.TupleExpr(items)), True
        return None, True

    # Special case: expr.__is_static__
    if member == "__is_static__":
        if expr.done:
            return wrap_side(
                ast.BoolExpr(isinstance(expr.type, ast.types.Type) and expr.type.get_static())
            ), True
        return None, True

    # Special case: cls.__id__
    if utils.is_type_expr(expr) and member == "__id__":
        if realized := infer.realize(utils.extract_type(self.ctx, expr)):
            return wrap_side(ast.IntExpr(utils.get_class_realization(self.ctx, realized).id)), True
        return None, True

    # Ensure that the type is known (otherwise wait until it becomes known)
    if expr_typ is None:
        return None, True

    # Check if this is a method or member access
    methods = utils.find_method(self.ctx, expr_typ, member)
    if not methods:
        return get_class_member(self, expr, member, typ)
    # If a method is ambiguous use dispatch
    best_method = (
        get_dispatch(self, utils.get_root_name(self.ctx, methods[0]))
        if len(methods) > 1
        else methods[0]
    )
    method_expr = ast.IdExpr(
        best_method.get_func_name(), type=utils.instantiate_type(self.ctx, best_method, expr_typ)
    )
    if utils.is_type_expr(expr):
        # Static access: `cls.method`
        return wrap_side(method_expr), True

    cls_data = utils.get_class(self.ctx, expr.type)
    method_ast = best_method.ast
    if (
        # check if the method is virtual
        cls_data
        and cls_data.rtti
        and (utils.get_unmangled_name(self.ctx, method_ast.name) in cls_data.virtuals)
        and (not utils.is_dispatch(best_method))
        and (not method_ast.has(ast.Attr.StaticMethod))
        and (not method_ast.has(ast.Attr.Property))
    ):
        best_method = get_thunk(self, best_method)
        method_expr = ast.IdExpr(
            best_method.get_func_name(),
            type=utils.instantiate_type(self.ctx, best_method, expr_typ),
        )
    if (
        parent
        and not method_ast.has(ast.Attr.StaticMethod)
        and not method_ast.has(ast.Attr.Property)
    ):
        # Instance access: `obj.method` from the call
        # Modify the call to push `self` to the front of the argument list.
        # Avoids creating partial functions.
        parent.items.insert(0, expr)
        return self.visit(method_expr), True
    else:
        # Instance access: `obj.method`
        # Transform y.method to a partial call `type(y).method(y, ...)`
        method_args = []
        # Do not add self if a method is marked with @staticmethod
        if not method_ast.has(ast.Attr.StaticMethod):
            method_args.append(expr)
        # If a method is marked with @property, just call it directly
        if not method_ast.has(ast.Attr.Property):
            method_args.append(ast.EllipsisExpr(ast.EllipsisExpr.PARTIAL))
        result = ast.CallExpr(method_expr, items=method_args)
        return self.visit(result), True


def check_capture(self: TypeVisitor, value: Item):
    """
    Access identifiers outside of the current function/class scope.
    Either use them as-is (globals), capture them if allowed (nonlocals),
    or raise an error.
    """

    if not self.ctx.is_outer(value):
        return
    if (value.is_type() and not value.is_generic()) or value.is_func():
        return
    base = self.ctx.get_base()
    # Ensure that outer variables can be captured (i.e., do not cross no-capture
    # boundary). Example:
    # def foo():
    # x = 1
    # class T:      # <- boundary (classes cannot capture locals)
    # t: int = x  # x cannot be accessed
    # def bar():  # <- another boundary
    # # (class methods cannot capture locals except class generics)
    # print(x)  # x cannot be accessed
    cross_capture_boundary = False
    local_generic = value.is_generic() and value.base_name == self.ctx.get_base_name()
    parent_class_generic = (
        value.is_generic()
        and not base.is_type()
        and len(self.ctx.bases) > 1
        and self.ctx.bases[-2].is_type()
        and self.ctx.bases[-2].name == value.base_name
    )
    idx = len(self.ctx.bases)
    while idx > 0:
        idx -= 1
        if self.ctx.bases[idx].name == value.base_name:
            break
        if not local_generic and not parent_class_generic:
            cross_capture_boundary = True

    # Mark methods (class functions that access class generics)
    if parent_class_generic:
        base.func.set(ast.Attr.Method)

    # Ignore generics
    if parent_class_generic or local_generic:
        return

    # Case: a global variable that has not been marked with `global` statement
    if value.is_var() and value.is_global():
        utils.register_global(self.ctx, value.canonical_name)
        return

    # Not in module; probably some capture
    if value.module_name != self.ctx.get_module():
        return

    # Check if a real variable (not a static) is defined outside the current scope
    if cross_capture_boundary:
        raise TypecheckError(
            self.ctx.node_stack[-1],
            f"name '{utils.get_user_facing_name(self.ctx, value.canonical_name)}' cannot be captured",
        )

    # Case: a nonlocal variable that has not been marked with `nonlocal` statement
    # and capturing is *not* enabled
    raise TypecheckError(
        self.ctx.node_stack[-1],
        f"no binding for nonlocal '{utils.get_user_facing_name(self.ctx, value.canonical_name)}' found",
    )


def get_import(self: TypeVisitor, chain: List[str]) -> Tuple[int, Item | None]:
    from . import TypeVisitor

    # 1. Find the longest prefix that corresponds to the existing import
    # (e.g., `a.b.c.d` -> `a.b.c` if there is `import a.b.c`)
    import_end, import_name = 0, ""
    value, import_value = None, None
    for idx in range(len(chain) - 1, -1, -1):
        name = "/".join(chain[: idx + 1])
        value = self.ctx.find(name, self.ctx.time)
        if value and value.type.is_type("Import") and value.canonical_name.startswith("%_import_"):
            import_name = utils.get_str_literal(value.type)
            import_end = idx + 1
            import_value = value
            break

    # Case: the whole chain is import itself
    if import_end == len(chain):
        return import_end, value

    # Find the longest prefix that corresponds to the existing class
    # (e.g., `a.b.c` -> `a.b` if there is `class a: class b:`)
    item_name, item_end = "", 0
    imported = None if not import_name else self.ctx.cache.imports.get(import_name)
    import_context = self.ctx if imported is None or imported.ctx is None else imported.ctx
    idx = len(chain) - 1
    while idx >= import_end:
        if import_context.get_module() == "std.python" and import_end < len(chain):
            # Special case: importing from Python.
            # Fake TypecheckItem that indicates std.python access
            return import_end, Item(
                module_name=import_context.get_module(),
                type=utils.instantiate_unbound(import_context),
            )

        key = ".".join(chain[import_end : idx + 1])
        # check only globals for imports
        value = import_context.find(key, 0, None if not import_name else "")
        if (
            value
            and idx + 1 != len(chain)
            and value.type.is_type("Import")
            and value.canonical_name.startswith("%_import_")
        ):
            import_name = utils.get_str_literal(value.type)
            import_end = idx + 1
            import_value = value
            imported = self.ctx.cache.imports.get(import_name)
            import_context = imported.ctx
            idx = len(chain) - 1
            continue

        is_overload = (
            value and value.is_func() and utils.has_overloads(self.ctx, value.canonical_name)
        )
        if is_overload and import_end == idx:  # top-level overload
            item_name = value.canonical_name
            item_end = idx + 1
            break

        # Class member
        if (
            value
            and not is_overload
            and (not import_name or value.is_type() or not value.is_conditional())
        ):
            item_name = value.canonical_name
            item_end = idx + 1
            break

        # Resolve the identifier from the import
        if import_item := self.ctx.find("Import"):
            import_type = utils.extract_class_type(self.ctx, import_item.type)
            if utils.find_member(self.ctx, import_type, key):
                return import_end, import_value
            if utils.find_method(self.ctx, import_type, key):
                return import_end, import_value
        idx -= 1

    if not item_name and not import_name:
        base = self.ctx.get_base()
        if base and base.py_captures is not None:
            return 1, None
        raise TypecheckError(self.ctx.node_stack[-1], f"no module named '{chain[import_end]}'")

    if not item_name:
        imported = self.ctx.cache.imports.get(import_name)
        if not self.ctx.is_stdlib_loading and import_name.endswith("__init__.codon"):
            # Special case: subimport is not yet loaded
            # (e.g., import a; a.b.x where a.b is a module as well)
            if self.ctx.cache.get_import_file(chain[import_end], import_name):
                # Auto-load support
                stmt = ast.SuiteStmt(ast.ImportStmt(ast.IdExpr(chain[import_end])))
                self.ctx.cache.scope(stmt)
                stmt = TypeVisitor(imported.ctx, preamble=self.preamble).visit(stmt)
                self.prepend_stmts.append(stmt)
                return get_import(self, chain)
        raise TypecheckError(
            self.ctx.node_stack[-1],
            f"cannot import name '{chain[import_end]}' from '{imported.name}'",
        )

    import_end = item_end
    return import_end, value


def get_dispatch(self: TypeVisitor, fn: str) -> ast.types.Function:
    """
    Find or generate an overload dispatch function for a given overload.
    Dispatch functions ensure that a function call is being routed to the correct
    overload
    even when dealing with partial functions and decorators.
    @example
    This is how dispatch looks like:
    ```def foo:dispatch(*args, **kwargs):
    return foo(*args, **kwargs)```
    """

    overloads = self.ctx.cache.overloads[fn]

    # Single overload: just return it
    if len(overloads) == 1:
        fn_data = utils.get_function(self.ctx, overloads[0])
        return fn_data.type

    # Check if dispatch exists
    for method in overloads:
        fn_data = utils.get_function(self.ctx, method)
        if fn_data and utils.is_dispatch(fn_data.ast):
            return fn_data.type

    # Dispatch does not exist. Generate it
    name = f"{fn}{cache.FN_DISPATCH_SUFFIX}"
    overloaded_fn = utils.get_function(self.ctx, overloads[0])
    parent_cls = overloaded_fn.ast.get(ast.Attr.ParentClass, "")
    # Root function name used for calling
    root = (
        ast.DotExpr(ast.IdExpr(parent_cls), member=utils.get_unmangled_name(self.ctx, fn))
        if parent_cls
        else ast.IdExpr(fn)
    )
    root = ast.CallExpr(
        root, items=[ast.StarExpr(ast.IdExpr("args")), ast.KeywordStarExpr(ast.IdExpr("kwargs"))]
    )
    args_name = self.ctx.generate_canonical_name("args")
    kwargs_name = self.ctx.generate_canonical_name("kwargs")
    node = ast.FunctionStmt(
        name,
        items=[ast.Param(f"*{args_name}"), ast.Param(f"**{kwargs_name}")],
        suite=ast.SuiteStmt(ast.ReturnStmt(expr=root)),
        done=True,
    )
    node.set(ast.Attr.AutoGenerated)
    node.set(ast.Attr.Module, self.ctx.module_name.path)
    if parent_cls:
        node.set(ast.Attr.ParentClass, parent_cls)
    self.ctx.cache.reverse_identifier_lookup[name] = utils.get_unmangled_name(self.ctx, fn)
    base_type = function.get_func_type_base(self, 2)
    fn_type = ast.types.Function(base=base_type.get_class(), ast=node)
    # Make sure that parent is set so that the parent type can be passed to the inner
    # call (e.g., A[B].foo -> A.foo.dispatch() { A[B].foo() })
    fn_type.func_parent = overloaded_fn.type.func_parent
    generalized = fn_type.generalize(self.ctx.typecheck_level - 1)
    self.ctx.add(name, name, generalized)
    overloads.insert(0, name)
    self.ctx.cache.functions[name] = cache.FunctionData(root_name=fn, ast=node, type=generalized)
    return generalized


def get_thunk(self: TypeVisitor, fn: ast.types.Function) -> ast.types.Function:
    """
    Find or generate a thunk function for a given method.
    @example
    This is how dispatch looks like:
    ```def foo:thunk(*args, **kwargs):
    return foo(*args, **kwargs)```
    """

    fn_name = fn.ast.name
    name = f"{fn_name}:thunk"
    fn_data = utils.get_function(self.ctx, name)
    if fn_data:
        return fn_data.type

    node = fn.ast.clone()
    node.name = name
    node.suite = ast.SuiteStmt(
        ast.AssignStmt(
            ast.IdExpr("F"),
            rhs=ast.CallExpr(
                ast.IdExpr(
                    ast.types.mangle("std.internal.static", cls="function", func="realized")
                ),
                items=[ast.IdExpr(fn_name)] + [ast.IdExpr(param.name) for param in node.items],
            ),
        ),
        ast.ReturnStmt(
            expr=ast.CallExpr(
                ast.CallExpr(
                    ast.CallExpr(ast.IdExpr(ast.types.Stdlib.Type), items=[ast.IdExpr("F")]),
                    items=[
                        ast.CallExpr(
                            ast.IdExpr(ast.types.mangle(cls="RTTIType", func="_find_thunk")),
                            items=[ast.IdExpr("self"), ast.IdExpr("F")],
                        )
                    ],
                ),
                items=[ast.IdExpr(param.name) for param in node.items],
            )
        ),
    )
    node.set(ast.Attr.Inline)
    node.set(ast.Attr.AutoGenerated)
    node.done = True

    self.ctx.cache.reverse_identifier_lookup[name] = utils.get_unmangled_name(self.ctx, fn_name)
    generalized = fn.generalize(self.ctx.typecheck_level - 1)
    generalized.ast = node
    self.ctx.add(name, name, generalized)
    self.ctx.cache.functions[name] = cache.FunctionData(
        root_name=fn_name, ast=node, type=generalized
    )
    return generalized


def get_class_member(
    self: TypeVisitor, expr: ast.Expr, member: str, typ: ast.types.Type | None = None
):
    """
    Find a class member.
    @example
    `obj.GENERIC`     -> `GENERIC` (IdExpr with generic/static value)
    `optional.member` -> `unwrap(optional).member`
    `pyobj.member`    -> `pyobj._getattr("member")`
    """

    class_type = utils.extract_class_type(self.ctx, expr)
    # Case: object member access (`obj.member`)
    if not utils.is_type_expr(expr):
        if class_member := utils.find_member(self.ctx, class_type, member):
            if typ and class_member.type:
                infer.unify(typ, utils.instantiate_type(self.ctx, class_member.type, class_type))
            cls_data = utils.get_class(self.ctx, class_type)
            if class_member.base_class != class_type.name and cls_data and cls_data.rtti:
                base_type = None
                for base in utils.get_base_classes(self.ctx, class_type):
                    base_class = base.get_class()
                    if base_class and base_class.name == class_member.base_class:
                        base_type = base
                        break
                assert base_type is not None, (
                    f"cannot find base type of {class_type.debug_string(2)}"
                )
                if not base_type.can_realize():
                    return None, True  # delay!
                realized_base = infer.realize(base_type)
                result = ast.DotExpr(
                    ast.CallExpr(
                        ast.IdExpr(ast.types.mangle(cls="RTTIType", func="_cast")),
                        items=[expr, ast.IdExpr(realized_base.realized_name())],
                    ),
                    member=member,
                )
                return self.visit(result), True
            if typ and not typ.can_realize() and class_member.type_expr:
                with utils.with_class_generics(self.ctx, class_type, lambda: None):
                    type_expr = self.visit(class_member.type_expr.clone())
                infer.unify(typ, utils.extract_type(self.ctx, type_expr))
            return None, True
    has_side = utils.has_side_effect(expr)

    def wrap_side(value: ast.Expr) -> ast.Expr:
        wrapped = ast.StmtExpr(ast.ExprStmt(expr), expr=value) if has_side else value
        return self.visit(wrapped)

    cls_data = utils.get_class(self.ctx, class_type)

    # Case: class variable (`Cls.var`)
    if cls_data and member in cls_data.class_vars:
        return wrap_side(ast.IdExpr(cls_data.class_vars[member])), True

    # Case: special members
    special_members = {
        "__elemsize__": "int",
        "__atomic__": "bool",
        "__contents_atomic__": "bool",
    }
    if member in special_members:
        if typ:
            infer.unify(typ, utils.get_stdlib_type(self.ctx, special_members[member]))
        return None, True
    if member == "__name__" and utils.is_type_expr(expr):
        if typ:
            infer.unify(typ, utils.get_stdlib_type(self.ctx, ast.types.Stdlib.String))
        return None, True

    # Case: object generic access (`obj.T`)
    generic = None
    for generic in class_type.generics:
        if member == utils.get_unmangled_name(self.ctx, generic.name):
            if generic.static_kind is not ast.types.Type.Behaviour.Runtime:
                if typ:
                    infer.unify(typ, generic.type)
                if infer.realize(generic.type):
                    return wrap_side(generic.type.get_static().get_static_expr()), True
            else:
                instantiated = utils.instantiate_type_var(self.ctx, generic.type)
                if typ:
                    infer.unify(typ, instantiated)
                if infer.realize(instantiated):
                    return wrap_side(ast.IdExpr(generic.type.realized_name())), True
            return None, True

    # Case: transform `optional.member` to `unwrap(optional).member`
    if class_type.is_type(ast.types.Stdlib.Optional):
        result = ast.DotExpr(
            ast.CallExpr(
                ast.IdExpr(ast.types.mangle(cls="Optional", func="__unwrap__")), items=[expr]
            ),
            member=member,
        )
        return self.visit(result), True

    # Case: transform `pyobj.member` to `pyobj._getattr("member")`
    if class_type.is_type("pyobj"):
        result = ast.CallExpr(ast.DotExpr(expr, member="_getattr"), items=[ast.StringExpr(member)])
        return self.visit(result), True

    # Case: NamedTuple support
    if class_type.is_type(ast.types.Stdlib.NamedTuple):
        tuple_id = utils.get_int_literal(class_type)
        assert 0 <= tuple_id < len(self.ctx.cache.generated_tuple_names)
        for idx, name in enumerate(self.ctx.cache.generated_tuple_names[tuple_id]):
            if name == member:
                result = ast.IndexExpr(ast.DotExpr(expr, member="args"), index=ast.IntExpr(idx))
                return self.visit(result), True

    # Case: __getattr__ support. Ensure that only Literal[str] arguments are accepted.
    unbound = utils.instantiate_unbound(self.ctx)
    unbound.static_kind = ast.types.Type.Behaviour.String
    method = utils.find_best_method(self.ctx, class_type, "__getattr__", [class_type, unbound])
    if method and len(method.func_generics) == 1:
        fn_generic = utils.extract_func_generic(method)
        if fn_generic.get_static_kind() is ast.types.Type.Behaviour.String:
            result = ast.CallExpr(
                ast.DotExpr(expr, member="__getattr__"), items=[ast.StringExpr(member)]
            )
            return self.visit(result), True

    # Case: name has an alternative identifier with more precise type. Use it.
    if isinstance(expr, ast.IdExpr):
        value = self.ctx.find(expr.value)
        if value and value.alternative:
            result = ast.DotExpr(ast.IdExpr(value.alternative.canonical_name), member=member)
            return self.visit(result), True

    return None, False
