# Copyright (C) 2022-2026 Exaloop Inc. <https://exaloop.io>

from __future__ import annotations

import copy
from typing import TYPE_CHECKING

from ....bridge import List, cast
from ... import ast, cache, error
from ...error import TypecheckError
from . import utils
from .ctx import Item, TypeContext

if TYPE_CHECKING:
    from . import TypeVisitor


def typecheck_class(self: TypeVisitor, node: ast.ClassStmt) -> ast.Node:
    """Parse a class (type) declaration and add a (generic) type to the context."""

    name = node.name
    canonical = ""
    args_to_parse = node.items

    # item will be added later when the scope is different
    item = Item(
        "",
        "",
        module=self.ctx.module_name,
        typ=ast.types.Type(self.ctx.cache),  # dummy
        block_level=self.ctx.block_level,
        info=node.info,
    )
    timed_item = None
    class_type: ast.types.Class | None = None
    if not node.has(ast.Attr.Extend):
        canonical = self.ctx.generate_canonical_name(
            name,
            not node.has(ast.Attr.Internal),
            no_suffix=node.has(ast.Attr.Internal),
        )
        item.canonical = canonical
        if canonical == ast.types.Stdlib.Union:
            item.type = ast.types.Union(cache=self.ctx.cache)
        else:
            item.type = ast.types.Class(cache=self.ctx.cache, name=canonical)
        class_type = item.type.require_cls
        if node.is_record():
            class_type.is_tuple = True
        item.type.info = node.info
        if canonical != ast.types.Stdlib.Type:
            item.type = utils.instantiate_type_var(self.ctx, item.type)
        timed_item = copy.copy(item)
        # Reference types are added to the context here.
        # Tuple types are added after class contents are parsed to prevent
        # recursive record types (note: these are allowed for reference types)
        if not node.has(ast.Attr.Tuple):
            self.ctx.add(name, timed_item)
            self.ctx.add_always_visible(item)
    else:
        # Find the canonical name and AST of the class that is to be extended
        if not self.ctx.is_global or self.ctx.is_conditional:
            raise TypecheckError(node, "class extension must be a top-level statement")
        value = self.ctx.find_at(name, self.ctx.time)
        if not value or not value.is_type:
            raise TypecheckError(node, f"class name '{name}' is not defined")
        class_type = (
            value.type.require_cls
            if value.canonical == ast.types.Stdlib.Type
            else utils.extract_class_type(self.ctx, value.type)
        )
        cls_data = utils.get_class(self.ctx, class_type)
        assert cls_data and cls_data.ast
        if cls_data.ast.has(ast.Attr.NoExtend):
            if not self.ctx.is_stdlib_loading and not node.has(ast.Attr.AutoGenerated):
                raise TypecheckError(node, f"'{name}' cannot be extended")
        canonical = class_type.name
        args_to_parse = cls_data.ast.items

    cls_data = self.ctx.cache.classes.setdefault(canonical, cache.ClassData())
    class_stmts = []
    var_stmts = []
    fn_stmts = []
    add_later = []
    try:
        with self.ctx.within_base(canonical):
            current_base = self.ctx.base
            current_base.type = class_type

            # Parse and add class generics
            args = []
            if node.has(ast.Attr.Extend):
                for arg in args_to_parse:
                    if not arg.is_generic():
                        continue
                    generic_item = self.ctx[arg.name]
                    generic_item.type.require_link.kind = ast.types.Link.Kind.Unbound
                    self.ctx.add(
                        utils.get_unmangled_name(self.ctx, generic_item.canonical),
                        generic_item,
                    )
                    args.append(ast.Param(generic_item.canonical, status=arg.status))
            else:
                if node.has(ast.Attr.ClassDeduce):
                    if not auto_deduce_members(self, node, args_to_parse):
                        node.erase(ast.Attr.ClassDeduce)
                # Add all generics before parent classes, fields and methods
                for arg in args_to_parse:
                    if not arg.is_generic():
                        continue
                    var_name = self.ctx.generate_canonical_name(arg.name)
                    generic_type = utils.instantiate_unbound(self.ctx)
                    type_id = generic_type.id
                    generic_type.generic_name = var_name
                    default_expr = (
                        self.visit_expr(arg.default.clone(), enforce_type=True)
                        if arg.default
                        else None
                    )
                    if default_expr:
                        generic_type.default_type = utils.extract_type(self.ctx, default_expr)

                    if (
                        static_kind := ast.get_static_generic(arg.type)
                    ) is not ast.types.Type.Behaviour.Runtime:
                        generic_type._static_kind = static_kind
                        generic_item = self.ctx.add_item(arg.name, var_name, generic_type)
                        generic_item.generic = True
                    else:
                        if isinstance(arg.type, ast.IndexExpr):
                            # Parse TraitVar
                            arg.type = self.visit_expr(arg.type)
                            assert (
                                isinstance(arg.type, ast.InstantiateExpr)
                                and isinstance(arg.type.expr, ast.IdExpr)
                                and arg.type.expr.value == ast.types.Stdlib.TypeTrait
                                and arg.type.items
                            ), "invalid type trait"
                            arg.type = arg.type
                            trait_type = utils.extract_type(self.ctx, arg.type.items[0])
                            generic_type.trait = (
                                trait_type
                                if isinstance(trait_type, ast.types.TypeTrait)
                                else ast.types.TypeTrait(trait_type)
                            )
                        generic_item = self.ctx.add_item(arg.name, var_name, generic_type)
                        generic_item.generic = True
                    class_type.generics.append(
                        ast.types.Generic(
                            var_name,
                            generic_type.generalize(self.ctx.typecheck_level),
                            type_id,
                            generic_type.static_kind,
                        )
                    )
                    args.append(
                        ast.Param(
                            var_name, type=arg.type, default_value=default_expr, status=arg.status
                        )
                    )

            # Form class type node (e.g. `Foo`, or `Foo[T, U]` for generic classes)
            type_expr = None
            if not node.has(ast.Attr.Extend):
                type_expr = ast.IdExpr(canonical)
                for arg in args:
                    if arg.is_generic():
                        if not isinstance(type_expr, ast.InstantiateExpr):
                            type_expr = ast.InstantiateExpr(ast.IdExpr(canonical))
                        type_expr.items.append(
                            self.visit_expr(ast.IdExpr(arg.name), type_allowed=True)
                        )

            # A ClassStmt will be separated into class variable assignments, method-free
            # ClassStmts (that include nested classes) and method FunctionStmts
            transform_nested_classes(self, node, class_stmts, var_stmts, fn_stmts)

            # Collect class fields
            for arg in args_to_parse:
                if arg.is_value() and ast.ClassStmt.is_class_var(arg):
                    # Handle class variables. Transform them later to allow self-references
                    var_name = f"{canonical}.{arg.name}"
                    declaration = self.visit(ast.AssignStmt(ast.IdExpr(var_name)))
                    self.ctx.preamble.add(declaration)
                    cls_var = self.ctx[var_name]
                    cls_var.base = ""
                    cls_var.block_level = 0
                    utils.register_global(self.ctx, cls_var.canonical)
                    if arg.default:
                        default = self.visit(arg.default)
                        annotated_type = (
                            None if not arg.type else cast(ast.IndexExpr, arg.type).index
                        )
                        var_stmts.append(
                            ast.AssignStmt(
                                ast.IdExpr(var_name),
                                rhs=default,
                                type_expr=annotated_type,
                                update=ast.AssignStmt.Mode.Update,
                            )
                        )
                    cls_data.class_vars[arg.name] = var_name
                    self.ctx.add(arg.name, cls_var)
                elif arg.is_value() and not node.has(ast.Attr.Extend):
                    var_name = arg.name
                    typ = (
                        self.visit_expr(
                            arg.type.clone(clean=True), enforce_type=True, simple_types=True
                        )
                        if arg.type
                        else None
                    )
                    default = (
                        self.visit_expr(arg.default.clone(), type_allowed=True)
                        if arg.default
                        else None
                    )
                    args.append(ast.Param(var_name, type=typ, default_value=default))
                    cls_data.fields.append(
                        cache.ClassData.Field(name=var_name, base_class=canonical)
                    )

            # Handle RTTI inheritance. Must come after other arguments are handled
            if not node.has(ast.Attr.Extend):
                parse_base_classes(self, node.base_classes, args, node, canonical, class_type)

            member_args = []
            arg_bases = {field.name: field.base_class for field in cls_data.fields}
            for arg in args:
                if arg.is_value() and arg_bases.get(arg.name, "") == canonical:
                    member_args.append(arg.clone())

            # Handle class members
            if not node.has(ast.Attr.Extend):
                # increase typecheck level to avoid unifying generics early
                with self.ctx.substitute("typecheck_level", self.ctx.typecheck_level + 1):
                    if canonical == ast.types.Stdlib.Tuple:
                        # Special tuple handling!
                        for field_idx in range(cache.MAX_TUPLE):
                            generic_name = f"T{field_idx + 1}"
                            generic_canonical_name = self.ctx.generate_canonical_name(generic_name)
                            tuple_generic = utils.instantiate_unbound(self.ctx)
                            tuple_generic.generic_name = generic_name
                            cls_data.fields.append(
                                cache.ClassData.Field(
                                    name=f"item{field_idx + 1}",
                                    type=tuple_generic.generalize(self.ctx.typecheck_level),
                                    type_expr=ast.IdExpr(generic_canonical_name),
                                )
                            )
                    else:
                        field_idx = 0
                        for arg in args:
                            if arg.is_value() and not ast.ClassStmt.is_class_var(arg):
                                cls_data.fields[field_idx].type_expr = arg.type.clone(True)
                                field_type = utils.extract_type(self.ctx, arg.type).generalize(
                                    self.ctx.typecheck_level - 1
                                )
                                field_type.info = arg.type.info
                                cls_data.fields[field_idx].type = field_type
                                field_idx += 1

            # Parse class members (arguments) and methods
            if not node.has(ast.Attr.Extend):
                # Now that we are done with arguments, add record type to the context
                if node.has(ast.Attr.Tuple):
                    self.ctx.add(name, timed_item)
                    self.ctx.add_always_visible(item)
                node.set(
                    ast.Attr.Module,
                    cache.STDLIB_IMPORT
                    if self.ctx.module.status is cache.Import.File.Status.StdLibrary
                    else self.ctx.module.path,
                )
                # Create a cached AST
                cached_ast = ast.ClassStmt(
                    canonical,
                    items=[argument.clone() for argument in args],
                    suite=ast.SuiteStmt(),
                    attributes=copy.deepcopy(node.attributes),
                    base_classes=node.base_classes,
                )
                cls_data.ast = cached_ast
                cls_data.module = self.ctx.module.path
                cls_data.jit_cell = self.ctx.cache.jit_cell

                # Codegen default magic methods
                if magics := node.get(ast.Attr.ClassMagic):
                    # __new__ must be the first
                    assert not magics or magics[0] == "new"
                    assert isinstance(magics, dict) and type_expr
                    for magic in magics:
                        magic_statement = codegen_magic(
                            self, magic, type_expr, member_args, node.has(ast.Attr.Tuple)
                        )
                        fn_stmts.append(self.visit(magic_statement))

            # Add class methods
            for stmt in get_class_methods(self, cast(ast.Stmt, node.suite)):
                if isinstance(stmt, ast.FunctionStmt):
                    for idx, decorator in enumerate(stmt.decorators):
                        match decorator:
                            case ast.DotExpr(ast.IdExpr(value=name), memver="setter") if (
                                name == stmt.name and len(stmt.items) == 2
                            ):
                                # Handle @setter setters
                                stmt.name = f"{cache.FN_SETTER_SUFFIX}{stmt.name}"
                                stmt.decorators[idx] = None
                                break
                    # All tuple methods are marked with AutoGenerated for later convenience
                    # (e.g. heterogenous tuple processing).
                    if canonical == ast.types.Stdlib.Tuple:
                        stmt.set(ast.Attr.AutoGenerated)
                    fn_stmts.append(self.visit(stmt))

            # After popping context block, record types and nested classes will disappear.
            # Store their references and re-add them to the context after popping
            add_later = [self.ctx[stmt.name] for stmt in class_stmts]
            if node.has(ast.Attr.Tuple):
                add_later.append(self.ctx[name])

            # Mark functions as virtual
            not_virtual = {
                "__init__",
                "__new__",
                "__raw__",
                "__tuplesize__",
                "__repr_default__",
            }
            for name in cls_data.methods:
                # Current class
                for mro_idx in range(1, len(cls_data.mro)):
                    base_name = cls_data.mro[mro_idx].name
                    base_class = utils.get_class(self.ctx, base_name)
                    assert base_class
                    if name in base_class.methods and name not in not_virtual:
                        cls_data.virtuals.add(name)
                # Parent class
                for virtual_name in cls_data.virtuals:
                    for mro_idx in range(1, len(cls_data.mro)):
                        base_class = utils.get_class(self.ctx, cls_data.mro[mro_idx].name)
                        assert base_class
                        base_class.virtuals.add(virtual_name)

            # Generalize generics and remove them from the context
            for arg in args:
                if not arg.is_value():
                    generic_item = self.ctx[arg.name]
                    generic_type = generic_item.type
                    if arg.status is ast.Param.Status.Generic:
                        # Generalize generics. Hidden generics are linked to the class generics so
                        # ignore them
                        assert generic_type.require_link.kind is not ast.types.Link.Kind.Link
                        generic_type.require_link.kind = ast.types.Link.Kind.Generic
                    self.ctx.remove(arg.name)

            # if not canonical_name.startswith("Tuple"):
            #     self.log(f"[class] {canonical_name} -> {class_type} / {len(cls_data.fields)}")
            #     for class_field in cls_data.fields:
            #         self.log(f"       - member: {class_field.name}: {class_field.type}")
            #     for name, method_root in cls_data.methods.items():
            #         self.log(f"       - method: {name}: {method_root}")
            #     for mro_type in cls_data.mro:
            #         self.log(f"       - mro: {mro_type}")
    except error.ParserError:
        if not node.has(ast.Attr.Tuple):
            self.ctx.remove(name)
        self.ctx.cache.classes.pop(name, None)
        raise
    for item in add_later:
        self.ctx.add(utils.get_unmangled_name(self.ctx, item.canonical), item)

    # Extensions are not needed as the cache is already populated
    if not node.has(ast.Attr.Extend):
        cls_ast = cls_data.ast
        assert cls_ast is not None, f"not a class AST for {canonical}"
        cls_ast.done = True
        class_stmts.append(cls_ast)
    class_stmts.extend(fn_stmts)
    for assignment in var_stmts:
        class_stmts.append(self.visit(assignment))
    return ast.SuiteStmt(*class_stmts)


def parse_base_classes(
    self: TypeVisitor,
    bases: List[ast.Expr],
    args: List[ast.Param],
    attr: ast.Stmt,
    canonical_name: str,
    typ: ast.types.Class,
) -> List[ast.types.Class]:
    """
    Parse statically inherited classes.
    Returns a list of their ASTs. Also updates the class fields.
    @param args Class fields that are to be updated with base classes' fields.
    """

    asts = []
    mro = [[typ]]
    for idx, base_expr in enumerate(bases):
        # Get the base class and generic replacements (e.g., if there is Bar[T],
        # Bar in Foo(Bar[int]) will have `T = int`)
        original = base_expr.clone()
        base_expr = bases[idx] = self.visit_expr(base_expr, enforce_type=True, simple_types=True)
        if not base_expr or not base_expr.cls:
            raise TypecheckError(
                attr,
                f"cannot use '{utils.get_unmangled_name(self.ctx, str(original))}' as a base class",
            )
        base_type = utils.extract_class_type(self.ctx, base_expr)
        base_data = utils.get_class(self.ctx, base_type)
        assert base_data
        if not base_data.ast:
            raise TypecheckError(attr, "nested classes cannot inherit surrounding classes")

        # Sanity checks
        if attr.has(ast.Attr.Tuple):
            raise TypecheckError(attr, "tuple classes cannot inherit other classes")
        if base_data.ast.has(ast.Attr.Tuple):
            raise TypecheckError(attr, "reference classes cannot inherit tuple classes")
        if base_data.ast.has(ast.Attr.Internal):
            raise TypecheckError(attr, "internal classes cannot inherit other classes")

        # Mark parent classes as polymorphic as well.
        if not base_data.rtti:
            if self.ctx.cache.is_jit and base_data.jit_cell != self.ctx.cache.jit_cell:
                raise TypecheckError(
                    base_expr,
                    f"cannot inherit from a non-RTTI class defined in previous cell '{utils.get_unmangled_name(self.ctx, base_type.name)}' in JIT mode",
                )
            base_data.rtti = True
            if base_type.name != ast.types.Stdlib.Object and len(base_data.mro) == 1:
                object_type = utils.get_stdlib_type(self.ctx, ast.types.Stdlib.Object)
                base_data.mro.append(object_type)

        root_mro = [utils.instantiate(self.ctx, typ, base_type) for typ in base_data.mro]
        mro.append(root_mro)
        asts.append(base_type.require_cls)

        # Add hidden generics
        utils.add_class_generics(self.ctx, base_type)
        for generic in base_type.generics:
            generic.type = generic.type.generalize(self.ctx.typecheck_level)
            typ.hidden_generics.append(generic)
        for generic in base_type.hidden_generics:
            generic.type = generic.type.generalize(self.ctx.typecheck_level)
            typ.hidden_generics.append(generic)

        # Add class variables
        for var_name, var_canonical in base_data.class_vars.items():
            # Handle class variables. Transform them later to allow self-references
            new_name = f"{canonical_name}.{var_name}"
            new_canonical = self.ctx.generate_canonical_name(new_name)
            cls_data = utils.get_class(self.ctx, typ)
            assert cls_data
            cls_data.class_vars[var_name] = var_canonical
            self.ctx.add(new_name, self.ctx[var_canonical])
            self.ctx.add(new_canonical, self.ctx[var_canonical])

    cls_data = utils.get_class(self.ctx, typ)
    assert cls_data
    if asts or typ.name == ast.types.Stdlib.Object:
        mro.append(asts)
        cls_data.rtti = True
    cls_data.mro = cache.Cache.merge_c3(mro)
    if not cls_data.mro:
        raise TypecheckError(attr, "inconsistent class hierarchy")
    asts = cls_data.mro  # use MRO order
    for mro_type in cls_data.mro:
        mro_class = utils.get_class(self.ctx, mro_type)
        assert mro_class
        mro_class.descendants.add(canonical_name)

    # Add normal fields
    for inherited_type in asts:
        if inherited_type == typ.name:
            continue
        inherited_data = utils.get_class(self.ctx, inherited_type)
        assert inherited_data
        with utils.with_class_generics(self.ctx, inherited_type):
            arg_idx = 0
            inherited_ast = inherited_data.ast
            assert inherited_ast
            for arg in inherited_ast:
                if arg.is_value() and not ast.ClassStmt.is_class_var(arg):
                    if inherited_data.fields[arg_idx].base_class == inherited_ast.name:
                        field_name = arg.name
                        for existing_arg in args:
                            if existing_arg.name == field_name:
                                raise TypecheckError(
                                    attr,
                                    f"field '{utils.get_unmangled_name(self.ctx, field_name)}' already defined",
                                )
                        args.append(
                            ast.Param(
                                field_name,
                                type=self.visit_expr(
                                    arg.type.clone(clean=True), enforce_type=True, simple_types=True
                                )
                                if arg.type
                                else None,
                                default=self.visit(arg.default.clone(clean=True))
                                if arg.default
                                else None,
                            )
                        )
                        extracted = utils.extract_type(self.ctx, args[-1].type)
                        cls_data.fields.append(
                            cache.ClassData.Field(
                                field_name, extracted, inherited_data.fields[arg_idx].base_class
                            )
                        )
                    arg_idx += 1
    return asts


def auto_deduce_members(self: TypeVisitor, node: ast.ClassStmt, args: List[ast.Param]):
    """
    Find the first __init__ with self parameter and use it to deduce class members.
    Each deduced member will be treated as generic.
    @example
    ```@deduce
    class Foo:
    def __init__(self):
    self.x, self.y = 1, 2```
    will result in
    ```class Foo[T1, T2]:
    x: T1
    y: T2```
    @return the transformed init and the pointer to the original function.
    """

    members = set()
    for stmt in get_class_methods(self, cast(ast.Stmt, node.suite)):
        match stmt:
            case ast.FunctionStmt(name="__init__"):
                if deduced := stmt.get(ast.Attr.ClassDeduce):
                    assert isinstance(deduced, list)
                    for member in deduced:
                        members.add(member)
    if members:
        if magics := node.get(ast.Attr.ClassMagic):
            assert isinstance(magics, list)
            magics[:] = [m for m in magics if m != "init"]
        for member in sorted(members):
            generic_name = f"T_{member}"
            args.append(
                ast.Param(
                    generic_name,
                    type=ast.IdExpr(ast.types.Stdlib.Type),
                    default_value=ast.IdExpr(ast.types.Stdlib.NoneType),
                    status=ast.Param.Status.Generic,
                )
            )
            args.append(ast.Param(member, type=ast.IdExpr(generic_name)))
        return True
    return False


def get_class_methods(self: TypeVisitor, node: ast.Stmt | None):
    """
    Return a list of all statements within a given class suite.
    Checks each suite recursively, and assumes that each statement is either
    a function, a class or a docstring.
    """
    match node:
        case None:
            return []
        case ast.SuiteStmt(items=items):
            for i in items:
                yield from get_class_methods(self, i)
        case ast.FunctionStmt() | ast.ClassStmt():
            yield node
        case ast.ExprStmt(expr=ast.StringExpr()):
            pass
        case _:
            raise TypecheckError(node, "unexpected expression in class definition")


def transform_nested_classes(
    self: TypeVisitor,
    node: ast.ClassStmt,
    cls_stmts: List[ast.Stmt],
    var_stmts: List[ast.Stmt],
    fn_stmts: List[ast.Stmt],
):
    """Extract nested classes and transform them before the main class."""

    # If class B is nested within A, it's name is always A.B, never B itself.
    # Ensure that parent class name is appended
    for stmt in get_class_methods(self, cast(ast.Stmt, node.suite)):
        if isinstance(stmt, ast.ClassStmt):
            orig_name = stmt.name
            parent_name = node.name
            stmt.name = f"{parent_name}.{orig_name}"
            transformed = self.visit(stmt)
            if isinstance(transformed, ast.SuiteStmt):
                name = ""
                for child in transformed.items:
                    if isinstance(child, ast.ClassStmt):
                        cls_stmts.append(child)
                        name = child.name
                    elif isinstance(child, ast.AssignStmt):
                        var_stmts.append(child)
                    else:
                        fn_stmts.append(child)
                self.ctx.add(orig_name, self.ctx[name])


def codegen_magic(
    self: TypeVisitor,
    magic: str,
    type_expr: ast.Expr,
    all_args: List[ast.Param],
    is_record: bool,
) -> ast.Stmt:
    """
    Generate a magic method `__op__` for each magic `op`
    described by @param typExpr and its arguments.
    Currently, generate:
    @li Constructors: __new__, __init__
    @li Utilities: __raw__, __hash__, __repr__, __tuplesize__, __add__, __mul__, __len__
    @li Iteration: __iter__, __getitem__, __len__, __contains__
    @li Comparisons: __eq__, __ne__, __lt__, __le__, __gt__, __ge__
    @li Pickling: __pickle__, __unpickle__
    @li Python: __to_py__, __from_py__
    @li GPU: __to_gpu__, __from_gpu__, __from_gpu_new__
    """

    ret = None
    fn_args = []
    stmts = []
    attrs = [ast.Attr.AutoGenerated]
    # Tuples: def __new__() -> T (internal)
    args = [arg.clone() for arg in all_args]

    M = lambda value: ast.DotExpr(ast.IdExpr("__magic__"), member=value)

    if magic == "new":
        ret = type_expr.clone()
        if is_record:
            # Tuples: def __new__() -> T (internal)
            for arg in args:
                fn_args.append(
                    ast.Param(
                        arg.name,
                        type=None if arg.type is None else arg.type.clone(),
                        default=None if arg.default is None else arg.default.clone(),
                    )
                )
            attrs.append(ast.Attr.Internal)
        else:
            # Classes: def __new__() -> T
            stmts.append(ast.ReturnStmt(expr=ast.CallExpr(M(magic), [type_expr.clone()])))
    elif magic == "init":
        # Classes: def __init__(self: T, a1: T1, ..., aN: TN) -> None:
        # self.aI = aI ...
        ret = ast.IdExpr(ast.types.Stdlib.NoneType)
        fn_args.append(ast.Param("self", type=type_expr.clone()))
        stmts.append(
            ast.IfStmt(
                ast.CallExpr(
                    ast.IdExpr(ast.types.mangle("std.internal.static", func="has_rtti")),
                    items=[type_expr.clone()],
                ),
                if_suite=ast.ExprStmt(
                    ast.CallExpr(
                        ast.DotExpr(ast.CallExpr(ast.IdExpr("super")), member="__init__"),
                        items=[
                            ast.StarExpr(ast.IdExpr("_args")),
                            ast.KeywordStarExpr(expr=ast.IdExpr("_kwargs")),
                        ],
                    )
                ),
            )
        )
        for arg in args:
            fn_args.append(
                ast.Param(
                    arg.name,
                    type=None if arg.type is None else arg.type.clone(True),
                    default=None if arg.default is None else arg.default.clone(),
                )
            )
            stmts.append(
                ast.AssignStmt(
                    ast.DotExpr(ast.IdExpr("self"), member=arg.name),
                    rhs=ast.IdExpr(arg.name),
                )
            )
        fn_args.append(ast.Param("*_args"))
        fn_args.append(ast.Param("**_kwargs"))
        attrs.append(ast.Attr.HasSelf)
    elif magic in {"raw", "dict"}:
        # Classes: def __raw__(self: T)
        fn_args.append(ast.Param("self", type=type_expr.clone()))
        stmts.append(ast.ReturnStmt(expr=ast.CallExpr(M(magic), [ast.IdExpr("self")])))
    elif magic == "tuplesize":
        # def __tuplesize__() -> int
        ret = ast.IdExpr("int")
        stmts.append(ast.ReturnStmt(expr=ast.CallExpr(M(magic))))
    elif magic == "getitem":
        # Tuples: def __getitem__(self: T, index: int)
        fn_args.extend(
            [ast.Param("self", type=type_expr.clone()), ast.Param("index", type=ast.IdExpr("int"))]
        )
        stmts.append(
            ast.ReturnStmt(expr=ast.CallExpr(M(magic), [ast.IdExpr("self"), ast.IdExpr("index")]))
        )
    elif magic == "iter":
        # Tuples: def __iter__(self: T)
        fn_args.append(ast.Param("self", type=type_expr.clone()))
        stmts.append(ast.YieldFromStmt(expr=ast.CallExpr(M(magic), [ast.IdExpr("self")])))
    elif magic == "contains":
        # Tuples: def __contains__(self: T, what) -> bool
        fn_args.extend([ast.Param("self", type=type_expr.clone()), ast.Param("what")])
        ret = ast.IdExpr(ast.types.Stdlib.Bool)
        stmts.append(
            ast.ReturnStmt(expr=ast.CallExpr(M(magic), [ast.IdExpr("self"), ast.IdExpr("what")]))
        )
    elif magic in {"eq", "ne", "lt", "le", "gt", "ge"}:
        # def __op__(self: T, obj: T) -> bool
        fn_args.extend(
            [ast.Param("self", type=type_expr.clone()), ast.Param("obj", type=type_expr.clone())]
        )
        ret = ast.IdExpr(ast.types.Stdlib.Bool)
        stmts.append(
            ast.ReturnStmt(expr=ast.CallExpr(M(magic), [ast.IdExpr("self"), ast.IdExpr("obj")]))
        )
    elif magic in {"hash", "len"}:
        # def __hash__(self: T) -> int
        fn_args.append(ast.Param("self", type=type_expr.clone()))
        ret = ast.IdExpr("int")
        stmts.append(ast.ReturnStmt(expr=ast.CallExpr(M(magic), [ast.IdExpr("self")])))
    elif magic == "pickle":
        # def __pickle__(self: T, dest: Ptr[byte])
        fn_args.extend(
            [
                ast.Param("self", type=type_expr.clone()),
                ast.Param(
                    "dest",
                    type=ast.IndexExpr(ast.IdExpr(ast.types.Stdlib.Ptr), index=ast.IdExpr("byte")),
                ),
            ]
        )
        stmts.append(
            ast.ReturnStmt(expr=ast.CallExpr(M(magic), [ast.IdExpr("self"), ast.IdExpr("dest")]))
        )
    elif magic in {"unpickle", "from_py"}:
        # def __unpickle__(src: Ptr[byte]) -> T
        fn_args.append(
            ast.Param(
                "src",
                type=ast.IndexExpr(ast.IdExpr(ast.types.Stdlib.Ptr), index=ast.IdExpr("byte")),
            )
        )
        ret = type_expr.clone()
        stmts.append(
            ast.ReturnStmt(expr=ast.CallExpr(M(magic), [ast.IdExpr("src"), type_expr.clone()]))
        )
    elif magic == "to_py":
        # def __to_py__(self: T) -> Ptr[byte]
        fn_args.append(ast.Param("self", type=type_expr.clone()))
        ret = ast.IndexExpr(ast.IdExpr(ast.types.Stdlib.Ptr), index=ast.IdExpr("byte"))
        stmts.append(ast.ReturnStmt(expr=ast.CallExpr(M(magic), [ast.IdExpr("self")])))
    elif magic == "to_gpu":
        # def __to_gpu__(self: T, cache) -> T
        fn_args.extend([ast.Param("self", type=type_expr.clone()), ast.Param("cache")])
        ret = type_expr.clone()
        stmts.append(
            ast.ReturnStmt(expr=ast.CallExpr(M(magic), [ast.IdExpr("self"), ast.IdExpr("cache")]))
        )
    elif magic == "from_gpu":
        # def __from_gpu__(self: T, other: T)
        fn_args.extend(
            [ast.Param("self", type=type_expr.clone()), ast.Param("other", type=type_expr.clone())]
        )
        stmts.append(
            ast.ReturnStmt(expr=ast.CallExpr(M(magic), [ast.IdExpr("self"), ast.IdExpr("other")]))
        )
    elif magic == "from_gpu_new":
        # def __from_gpu_new__(other: T) -> T
        fn_args.append(ast.Param("other", type=type_expr.clone()))
        ret = type_expr.clone()
        stmts.append(ast.ReturnStmt(expr=ast.CallExpr(M(magic), [ast.IdExpr("other")])))
    elif magic in {"repr", "repr_default"}:
        # def __repr__(self: T) -> str
        # def __repr_default__(self: T) -> str
        fn_args.append(ast.Param("self", type=type_expr.clone()))
        ret = ast.IdExpr(ast.types.Stdlib.String)
        stmts.append(ast.ReturnStmt(expr=ast.CallExpr(M(magic), [ast.IdExpr("self")])))
    elif magic == "add":
        # def __add__(self: TypeVisitor, obj)
        fn_args.extend([ast.Param("self", type=type_expr.clone()), ast.Param("obj")])
        stmts.append(
            ast.ReturnStmt(expr=ast.CallExpr(M(magic), [ast.IdExpr("self"), ast.IdExpr("obj")]))
        )
    elif magic == "mul":
        # def __mul__(self: TypeVisitor, i: Literal[int])
        fn_args.extend(
            [
                ast.Param("self", type=type_expr.clone()),
                ast.Param("i", type=ast.IndexExpr(ast.IdExpr("Literal"), index=ast.IdExpr("int"))),
            ]
        )
        stmts.append(
            ast.ReturnStmt(expr=ast.CallExpr(M(magic), [ast.IdExpr("self"), ast.IdExpr("i")]))
        )
    else:
        assert False, f"invalid magic {magic}"

    fn = ast.FunctionStmt(f"__{magic}__", ret=ret, items=fn_args, suite=ast.SuiteStmt(*stmts))
    for attribute in attrs:
        fn.set(attribute)
    return fn


def generate_kw_id(self: TypeVisitor, names: List[str] | None = None) -> int:
    if names:
        key = ";".join(names)
        # Each set of names generates different tuple (i.e., `KwArgs[foo, bar]` is not the
        # same as `KwArgs[bar, baz]`). Cache the names and use an integer for each name
        # combination.
        if key not in self.ctx.cache.generated_kw_tuples:
            self.ctx.cache.generated_tuple_names.append(names)
            self.ctx.cache.generated_kw_tuples[key] = len(self.ctx.cache.generated_kw_tuples) + 1
        return self.ctx.cache.generated_kw_tuples[key]
    return 0


def generate_tuple(ctx: TypeContext, count: int, generate_new: bool = True) -> ast.types.Class:
    if count > cache.MAX_TUPLE:
        raise TypecheckError(ctx.node_stack[-1], f"tuple too large ({count})")
    key = f"{ast.types.Stdlib.Tuple}.{count}"
    stdlib = utils.get_import_module(ctx, cache.STDLIB_IMPORT)
    value = stdlib.ctx.get(key)
    if not value:
        tuple_type = ast.types.Class(cache=ctx.cache, name=ast.types.Stdlib.Tuple)
        tuple_type.is_tuple = True
        cls_data = utils.get_class(ctx, tuple_type)
        assert cls_data is not None and count <= len(cls_data.fields), "tuple too large"
        for idx in range(count):
            field = cls_data.fields[idx]
            assert isinstance(field.type_expr, ast.IdExpr)
            tuple_type.generics.append(
                ast.types.Generic(
                    field.type_expr.value,
                    field.type,
                    field.type.require_link.id,
                    ast.types.Type.Behaviour.Runtime,
                )
            )
        value = stdlib.ctx.add_item(key, key, tuple_type)

    result = value.type.require_cls
    if generate_new and count not in ctx.cache.generated_tuples:
        ctx.cache.generated_tuples.add(count)
        new_args = []
        type_args = []
        for idx in range(count):
            new_args.append(ast.Param(f"item{idx + 1}", type=ast.IdExpr(f"T{idx + 1}")))
            type_args.append(ast.IdExpr(f"T{idx + 1}"))
        for idx in range(count):
            new_args.append(ast.Param(f"T{idx + 1}", type=ast.IdExpr(ast.types.Stdlib.Type)))
        fn = ast.FunctionStmt(
            "__new__",
            ret=ast.IndexExpr(ast.IdExpr(ast.types.Stdlib.Tuple), index=ast.TupleExpr(type_args)),
            items=new_args,
        )
        fn.set(ast.Attr.Internal)

        extension = ast.ClassStmt(ast.types.Stdlib.Tuple, suite=fn)
        extension.set(ast.Attr.Extend)
        extension.set(ast.Attr.AutoGenerated)
        extension = ast.SuiteStmt(extension)
        ctx.cache.scope(extension)

        with (
            stdlib.ctx.substitute("bases", [stdlib.ctx.bases[0]]),
            stdlib.ctx.substitute("block_level", 0),
            stdlib.ctx.substitute("preamble", ctx.preamble),
        ):
            extension = ctx.cache.typecheck(extension, ctx=stdlib.ctx)
            ctx.preamble.add(extension)
    return result
