#!/usr/bin/env python3
import argparse
from pathlib import Path

POW5_INV_BITCOUNT = 125
POW5_BITCOUNT = 125

# Required by binary64 Ryū conversion.
POW5_INV_TABLE_SIZE = 292
POW5_TABLE_SIZE = 326

MASK64 = (1 << 64) - 1


def pow5bits(exponent: int) -> int:
    """Return floor(log2(5**exponent)) + 1."""
    return ((exponent * 1217359) >> 19) + 1


def split_u128(value: int) -> tuple[int, int]:
    return value & MASK64, value >> 64


def compute_pow5_inverse(exponent: int) -> tuple[int, int]:
    """
    Return ceil(2**k / 5**exponent), where k gives a 125-bit cached power.

    The added one is intentional and matches Ryū's generated inverse table.
    """
    k = pow5bits(exponent) - 1 + POW5_INV_BITCOUNT
    value = (1 << k) // (5**exponent) + 1
    return split_u128(value)


def compute_pow5(exponent: int) -> tuple[int, int]:
    """Return floor(5**exponent / 2**k) as a 125-bit cached power."""
    k = pow5bits(exponent) - POW5_BITCOUNT
    value = 5**exponent

    if k >= 0:
        value >>= k
    else:
        value <<= -k

    return split_u128(value)


def llvm_array(values: list[int]) -> str:
    return ", ".join(f"i64 {value}" for value in values)


def emit_accessor(
    output,
    name: str,
    values: list[int],
) -> None:
    output.write(
        f"""
@pure
@llvm
def {name}(index: int) -> u64:
    @data = private unnamed_addr constant [{len(values)} x i64] [{llvm_array(values)}]
    %p = getelementptr inbounds [{len(values)} x i64], ptr @data, i64 0, i64 %index
    %x = load i64, ptr %p, align 8
    ret i64 %x
"""
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("stdlib/internal/unicode/float_dtoa_tables.codon"),
    )
    args = parser.parse_args()

    inverse_powers = [
        compute_pow5_inverse(exponent)
        for exponent in range(POW5_INV_TABLE_SIZE)
    ]
    powers = [
        compute_pow5(exponent) for exponent in range(POW5_TABLE_SIZE)
    ]

    args.output.parent.mkdir(parents=True, exist_ok=True)

    with args.output.open("w", encoding="utf-8") as output:
        output.write(
            f"""# AUTO-GENERATED by scripts/generate_float_dtoa_tables.py.
# Do not edit manually.

FLOAT_DTOA_POW5_INV_BITCOUNT: Literal[int] = {POW5_INV_BITCOUNT}
FLOAT_DTOA_POW5_BITCOUNT: Literal[int] = {POW5_BITCOUNT}
FLOAT_DTOA_POW5_INV_TABLE_SIZE: Literal[int] = {POW5_INV_TABLE_SIZE}
FLOAT_DTOA_POW5_TABLE_SIZE: Literal[int] = {POW5_TABLE_SIZE}
"""
        )

        emit_accessor(
            output,
            "_float_dtoa_pow5_inv_lo",
            [lo for lo, _ in inverse_powers],
        )
        emit_accessor(
            output,
            "_float_dtoa_pow5_inv_hi",
            [hi for _, hi in inverse_powers],
        )
        emit_accessor(
            output,
            "_float_dtoa_pow5_lo",
            [lo for lo, _ in powers],
        )
        emit_accessor(
            output,
            "_float_dtoa_pow5_hi",
            [hi for _, hi in powers],
        )


if __name__ == "__main__":
    main()
