#!/usr/bin/env python3
"""Generate LLVM lookup tables for single-byte codecs."""

import argparse
import codecs
import pathlib


DEFAULT_CODECS = ("cp1250", "cp1253", "cp1254")


def codec_name(name: str) -> str:
    return name.replace("-", "_")


def decode_table(name: str) -> list[int]:
    values = []

    for byte in range(256):
        try:
            decoded = bytes([byte]).decode(name)
        except UnicodeDecodeError:
            values.append(-1)
            continue

        if len(decoded) != 1:
            raise ValueError(f"{name} maps byte {byte:#x} to multiple code points")
        values.append(ord(decoded))

    return values


def find_perfect_hash(entries: list[tuple[int, int]]) -> tuple[int, int, int]:
    size = 1
    while size < len(entries) * 2:
        size <<= 1

    while size <= 16384:
        mask = size - 1
        for shift in range(32):
            for multiplier in range(1, 65536):
                slots = set()
                for codepoint, _ in entries:
                    slot = ((codepoint * multiplier) >> shift) & mask
                    if slot in slots:
                        break
                    slots.add(slot)
                else:
                    return size, multiplier, shift
        size <<= 1

    raise ValueError("unable to find a perfect hash")


def llvm_values(values: list[int], llvm_type: str) -> str:
    return ", ".join(f"{llvm_type} {value}" for value in values)


def emit_codec(out, name: str):
    symbol = codec_name(name)
    decoded = decode_table(name)
    entries = [(codepoint, byte) for byte, codepoint in enumerate(decoded) if codepoint >= 0]
    size, multiplier, shift = find_perfect_hash(entries)
    packed = [0] * size

    for codepoint, byte in entries:
        index = ((codepoint * multiplier) >> shift) & (size - 1)
        packed[index] = (codepoint << 8) | byte

    out.write(
        f"""
@pure
@llvm
def _single_byte_{symbol}_decode(byte: int) -> i32:
    @data = private unnamed_addr constant [256 x i32] [{llvm_values(decoded, "i32")}]
    %p = getelementptr inbounds [256 x i32], ptr @data, i64 0, i64 %byte
    %value = load i32, ptr %p, align 4
    ret i32 %value


@pure
@llvm
def _single_byte_{symbol}_encode(codepoint: int) -> i32:
    @data = private unnamed_addr constant [{size} x i64] [{llvm_values(packed, "i64")}]
    %product = mul i64 %codepoint, {multiplier}
    %shifted = lshr i64 %product, {shift}
    %index = and i64 %shifted, {size - 1}
    %p = getelementptr inbounds [{size} x i64], ptr @data, i64 0, i64 %index
    %packed = load i64, ptr %p, align 8
    %stored = lshr i64 %packed, 8
    %matched = icmp eq i64 %stored, %codepoint
    %byte = trunc i64 %packed to i32
    %result = select i1 %matched, i32 %byte, i32 -1
    ret i32 %result
"""
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=pathlib.Path("stdlib/internal/types/unicode/codecs.codon"),
    )
    parser.add_argument(
        "--codecs",
        default=",".join(DEFAULT_CODECS),
        help="Comma-separated Python codec names",
    )
    args = parser.parse_args()
    names = tuple(name.strip() for name in args.codecs.split(",") if name.strip())

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as out:
        out.write(
            "# AUTO-GENERATED by scripts/generate_single_byte_codecs.py.\n"
            "# Do not edit manually.\n"
        )
        for name in names:
            codecs.lookup(name)
            emit_codec(out, name)


if __name__ == "__main__":
    main()
