# Copyright (C) 2022-2026 Exaloop Inc. <https://exaloop.io
# Copyright (C) 2022-2026 Exaloop Inc. <https://exaloop.io>
from __future__ import annotations
from typing import Dict, List, Set

from collections.abc import Iterator
from dataclasses import dataclass
from enum import Enum
import copy

from .types import Literal

class Attr(Enum):
    """Codon AST node attribute."""

    Module = 201
    ParentClass = 202
    Bindings = 203
    LLVM = 204
    Python = 205
    Atomic = 206
    Property = 207
    StaticMethod = 208
    Attribute = 209
    C = 210
    Internal = 211
    HiddenFromUser = 212
    ForceRealize = 213
    AllowPassThrough = 214
    ParentCallExpr = 215
    TupleCall = 216
    Validated = 217
    AutoGenerated = 218
    CVarArg = 219
    Method = 220
    Capture = 221
    HasSelf = 222
    IsGenerator = 223
    Extend = 224
    Tuple = 225
    Dataclass = 226
    ClassDeduce = 227
    ClassNoTuple = 228
    Test = 229
    Overload = 230
    Export = 231
    Inline = 232
    NoArgReorder = 233
    FunctionAttributes = 234
    NoExtend = 235
    ClassMagic = 236
    ExprSequenceItem = 237
    ExprStarSequenceItem = 238
    ExprList = 239
    ExprSet = 240
    ExprDict = 241
    ExprPartial = 242
    ExprDominated = 243
    ExprStarArgument = 244
    ExprKwStarArgument = 245
    ExprOrderedCall = 246
    ExprExternVar = 247
    ExprNoUndefCheck = 248
    ExprDominatedUsed = 249
    ExprTime = 250
    ExprDoNotRealize = 251
    ExprNoSpecial = 252
    TryPyVar = 253
    LocalRenames = 254


class Node:
    """Base class for parser AST nodes."""

    @dataclass
    class SrcInfo:
        file: str = ""
        line: int = 0
        col: int = 0
        length: int = 0

    info: Node.SrcInfo
    attributes: Dict[Attr, object]
    cache: object | None = None

    def clone(self, clean: bool = False):
        """Deep copy a node."""
        result = copy.deepcopy(self)
        if clean:
            result.attributes.clear()
            result.cache = None
        return result

    def accept(self, visitor):
        method = getattr(visitor, f"visit_{type(self).__name__}", None)
        return visitor.default_visit(self) if method is None else method(self)

    def set(self, key: Attr, value=True):
        self.attributes[key] = value

    def has(self, key: Attr):
        return key in self.attributes

    def get(self, key: Attr, default=None):
        return self.attributes.get(key, default)

    def erase(self, key: Attr):
        self.attributes.pop(key, None)


@dataclass(init=False)
class Expr(Node):
    # Type of the expression.
    type: object | None = None
    # Flag that indicates if all types in an expression are inferred
    # (i.e. if a type-checking procedure was successful).
    done: bool = False
    # Original (pre-transformation) expression
    orig: Expr | None = None
    # Expected type of the expression.
    expected_type: object | None = None

    def __init__(
        self,
        type: object | None = None,
        done: bool = False,
        orig: Expr | None = None,
        expected_type: object | None = None,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.type = type
        self.done = done
        self.orig = orig
        self.expected_type = expected_type

    def get_class_type(self) -> object | None:
        return self.type.get_class() if self.type else None


@dataclass(init=False)
class Param(Node):
    """Function signature parameter helper node (name: type = defaultValue)."""

    class Status(Enum):
        Value = 0
        Generic = 1
        HiddenGeneric = 2

    name: str = ""
    type: Expr | None = None
    default: Expr | None = None
    status: Param.Status = Status.Value

    def __init__(
        self,
        name: str = "",
        type: Expr | None = None,
        default: Expr | None = None,
        status: Param.Status = Status.Value,
        **kwargs,
    ):
        super().__init__(**kwargs)

        self.name = name
        self.type = type
        self.default = default
        self.status = status

        if self.status is Param.Status.Value:
            match self.type:
                case (
                    IdExpr(value="type" | "TypeTrait")
                    | IndexExpr(expr=IdExpr(value="TypeTrait"))
                ):
                    self.status = Param.Status.Generic
                case _:
                    static_kind = get_static_generic(self.type)
                    if static_kind is not Literal.Kind.Runtime:
                        self.status = Param.Status.Generic

    def is_value(self):
        return self.status is Param.Status.Value

    def is_generic(self):
        return self.status is Param.Status.Generic

    def is_hidden_generic(self):
        return self.status is Param.Status.HiddenGeneric

    def get_name_with_stars(self):
        stars = len(self.name) - len(self.name.lstrip("*"))
        return stars, self.name[stars:]


@dataclass(init=False)
class NoneExpr(Expr):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)


@dataclass(init=False)
class BoolExpr(Expr):
    value: bool = False

    def __init__(self, value: bool = False, **kwargs):
        super().__init__(**kwargs)
        self.value = value


@dataclass(init=False)
class IntExpr(Expr):
    # Expression value is stored as a string that is parsed during typechecking.
    value: str = ""
    # Number suffix (e.g. "u" for "123u").
    suffix: str = ""
    # Parsed value and sign for "normal" 64-bit integers.
    int_value: int | None = None

    def __init__(
        self, value: str = "", suffix: str = "", int_value: int | None = None, **kwargs
    ):
        super().__init__(**kwargs)
        self.value = value
        self.suffix = suffix
        self.int_value = int_value

        if not self.value:
            if self.int_value is None:
                self.int_value = 0
            self.value = str(self.int_value)
        else:
            self.int_value = None
            self.value = self.value.replace("_", "")
            try:
                if self.value.startswith(("0b", "0B")):
                    self.int_value = int(self.value, 2)
                elif self.value.startswith(("0o", "0O")):
                    self.int_value = int(self.value, 8)
                elif self.value.startswith(("0x", "0X")):
                    self.int_value = int(self.value, 16)
                else:
                    self.int_value = int(self.value, 0)
                if self.int_value < 0 or self.int_value > (1 << 64) - 1:
                    self.int_value = None
            except ValueError:
                pass

    def has_stored_value(self):
        return self.int_value is not None

    def get_value(self) -> int:
        if self.int_value is None:
            raise ValueError("integer has not been parsed")
        return self.int_value

    def get_raw_data(self):
        return self.value, self.suffix


@dataclass(init=False)
class FloatExpr(Expr):
    # Expression value is stored as a string that is parsed during typechecking.
    value: str = ""
    # Number suffix (e.g. "u" for "123u").
    suffix: str = ""
    # Parsed value for 64-bit floats.
    float_value: float | None = None

    def __init__(
        self,
        value: str = "",
        suffix: str = "",
        float_value: float | None = None,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.value = value
        self.suffix = suffix
        self.float_value = float_value

        if not self.value:
            if self.float_value is None:
                self.float_value = 0.0
            self.value = f"{self.float_value:g}"
            return
        else:
            self.float_value = None
            self.value = self.value.replace("_", "")
            try:
                self.float_value = float(self.value)
            except ValueError:
                pass

    def has_stored_value(self):
        return self.float_value is not None

    def get_value(self) -> float:
        if self.float_value is None:
            raise ValueError("float has not been parsed")
        return self.float_value

    def get_raw_data(self):
        return self.value, self.suffix


@dataclass(init=False)
class StringExpr(Expr):
    @dataclass
    class FormatSpec:
        text: str = ""
        conversion: str = ""
        spec: str = ""

    @dataclass
    class String(Node):
        """Vector of {value, prefix} strings."""

        value: str = ""
        prefix: str = ""
        expr: Expr | None = None
        format: StringExpr.FormatSpec

        def __init__(
            self,
            value: str = "",
            prefix: str = "",
            expr: Expr | None = None,
            format: StringExpr.FormatSpec | None = None,
            **kwargs,
        ):
            super().__init__(**kwargs)
            self.value = value
            self.prefix = prefix
            self.expr = expr
            self.format = StringExpr.FormatSpec() if format is None else format

    strings: List[StringExpr.String]
    value: str = ""
    prefix: str = ""

    def __init__(
        self,
        strings: List[String] | None = None,
        value: str = "",
        prefix: str = "",
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.strings = [] if strings is None else strings
        self.value = value
        self.prefix = prefix
        if not self.strings:
            self.strings = [StringExpr.String(value=self.value, prefix=self.prefix)]

    def __iter__(self) -> Iterator[String]:
        yield from self.strings

    @property
    def is_simple(self):
        return len(self.strings) == 1 and not self.strings[0].prefix

    def get_value(self) -> str:
        assert self.is_simple(), "invalid StringExpr"
        return self.strings[0].value


@dataclass(init=False)
class IdExpr(Expr):
    value: str = ""

    def __init__(self, value: str = "", **kwargs):
        super().__init__(**kwargs)
        self.value = value


@dataclass(init=False)
class StarExpr(Expr):
    expr: Expr | None = None

    def __init__(self, expr: Expr | None = None, **kwargs):
        super().__init__(**kwargs)
        self.expr = expr


@dataclass(init=False)
class KeywordStarExpr(StarExpr):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)


@dataclass(init=False)
class TupleExpr(Expr):
    items: List[Expr]

    def __init__(self, items: List[Expr] | None = None, **kwargs):
        super().__init__(**kwargs)
        self.items = [] if items is None else items


@dataclass(init=False)
class ListExpr(TupleExpr):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)


@dataclass(init=False)
class SetExpr(TupleExpr):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)


@dataclass(init=False)
class DictExpr(TupleExpr):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        for item in self.items:
            assert isinstance(item, TupleExpr) and len(item.items) == 2, (
                "dictionary items are invalid"
            )


@dataclass(init=False)
class GeneratorExpr(Expr):
    class Kind(Enum):
        Generator = 0
        ListGenerator = 1
        SetGenerator = 2
        TupleGenerator = 3
        DictGenerator = 4

    kind: GeneratorExpr.Kind = Kind.Generator
    loops: object | None = None

    def __init__(
        self,
        kind: GeneratorExpr.Kind = Kind.Generator,
        loops: object | None = None,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.kind = kind
        self.loops = loops

    def iter_blocks(self, for_fn=None, if_fn=None, expr_fn=None):
        i = self.loops
        while True:
            match i:
                case ForStmt(suite=s):
                    if for_fn:
                        for_fn(i)
                    i = s
                case IfStmt(suite=s):
                    if if_fn:
                        if_fn(i)
                    i = s
                case SuiteStmt(stmts=[*_, ExprStmt(value=e)]):
                    if expr_fn:
                        expr_fn(e)
                    return
                case SuiteStmt(stmts=[*_, s]):
                    i = s
                case _:
                    return

    def loop_count(self):
        cnt = 0

        def inc(s):
            nonlocal cnt
            cnt += 1

        self.iter_blocks(for_fn=inc, if_fn=inc)
        return cnt

    def final_expr(self):
        expr = None

        def catch(e):
            nonlocal expr
            expr = e

        self.iter_blocks(expr_fn=catch)
        return expr

    def final_suite(self):
        return self.loops


@dataclass(init=False)
class IfExpr(Expr):
    cond: Expr | None = None
    ifexpr: Expr | None = None
    elsexpr: Expr | None = None

    def __init__(
        self,
        cond: Expr | None = None,
        ifexpr: Expr | None = None,
        elsexpr: Expr | None = None,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.cond = cond
        self.ifexpr = ifexpr
        self.elsexpr = elsexpr


@dataclass(init=False)
class UnaryExpr(Expr):
    op: str = ""
    expr: Expr | None = None

    def __init__(self, op: str = "", expr: Expr | None = None, **kwargs):
        super().__init__(**kwargs)
        self.op = op
        self.expr = expr


@dataclass(init=False)
class BinaryExpr(Expr):
    lexpr: Expr | None = None
    op: str = ""
    rexpr: Expr | None = None
    # True if an expression modifies lhs in-place (e.g. a += b).
    in_place: bool = False

    def __init__(
        self,
        lexpr: Expr | None = None,
        op: str = "",
        rexpr: Expr | None = None,
        in_place: bool = False,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.lexpr = lexpr
        self.op = op
        self.rexpr = rexpr
        self.in_place = in_place


@dataclass(init=False)
class ChainBinaryExpr(Expr):
    exprs: List[tuple[str, Expr]]

    def __init__(self, exprs: List[tuple[str, Expr]] | None = None, **kwargs):
        super().__init__(**kwargs)
        self.exprs = [] if exprs is None else exprs


@dataclass(init=False)
class PipeExpr(Expr):
    @dataclass
    class Pipe(Node):
        op: str = ""
        expr: Expr | None = None

    items: List[PipeExpr.Pipe]
    # Output type of a "prefix" pipe ending at the index position.
    # Example: for a |> b |> c, inTypes[1] is typeof(a |> b).
    in_types: List[object]

    def __init__(
        self,
        items: List[PipeExpr.Pipe] | None = None,
        in_types: List[object] | None = None,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.items = [] if items is None else items
        self.in_types = [] if in_types is None else in_types
        for item in self.items:
            if isinstance(item.expr, CallExpr):
                for argument in item.expr.items:
                    if isinstance(argument.value, EllipsisExpr):
                        argument.value.mode = EllipsisExpr.Kind.Pipe


@dataclass(init=False)
class IndexExpr(Expr):
    expr: Expr | None = None
    index: Expr | None = None

    def __init__(self, expr: Expr | None = None, index: Expr | None = None, **kwargs):
        super().__init__(**kwargs)
        self.expr = expr
        self.index = index


@dataclass(init=False)
class CallExpr(Expr):
    @dataclass(init=False)
    class Arg(Node):
        name: str = ""
        value: Expr | None = None

        def __init__(self, name: str = "", value: Expr | None = None, **kwargs):
            super().__init__(**kwargs)
            self.name = name
            self.value = value
            if self.value is not None and self.info == Node.SrcInfo():
                self.info = self.value.info

    expr: Expr | None = None
    items: List[CallExpr.Arg]
    # True if type-checker has processed and re-ordered args.
    ordered: bool = False
    # True if the call is partial.
    partial: bool = False

    def __init__(
        self,
        expr: Expr | None = None,
        items: List | None = None,
        ordered: bool = False,
        partial: bool = False,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.items = []
        if items:
            for i in items:
                if isinstance(i, CallExpr.Arg):
                    self.items.append(i)
                else:
                    self.items.append(CallExpr.Arg("", i))
        self.expr = expr
        self.ordered = ordered
        self.partial = partial


@dataclass(init=False)
class DotExpr(Expr):
    expr: Expr | None = None
    member: str = ""

    def __init__(self, expr: Expr | None = None, member: str = "", **kwargs):
        super().__init__(**kwargs)
        self.expr = expr
        self.member = member


@dataclass(init=False)
class SliceExpr(Expr):
    start: Expr | None = None
    stop: Expr | None = None
    step: Expr | None = None

    def __init__(
        self,
        start: Expr | None = None,
        stop: Expr | None = None,
        step: Expr | None = None,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.start = start
        self.stop = stop
        self.step = step


@dataclass(init=False)
class EllipsisExpr(Expr):
    class Kind(Enum):
        Pipe = 0
        Partial = 1
        Standalone = 2

    mode: EllipsisExpr.Kind = Kind.Standalone

    def __init__(self, mode: EllipsisExpr.Kind = Expr.Kind.Standalone, **kwargs):
        super().__init__(**kwargs)
        self.mode = mode

    def is_standalone(self):
        return self.mode is EllipsisExpr.Kind.Standalone

    def is_pipe(self):
        return self.mode is EllipsisExpr.Kind.Pipe

    def is_partial(self):
        return self.mode is EllipsisExpr.Kind.Partial


@dataclass(init=False)
class LambdaExpr(Expr):
    items: List[Param]
    expr: Expr | None = None

    def __init__(
        self, items: List[Param] | None = None, expr: Expr | None = None, **kwargs
    ):
        super().__init__(**kwargs)
        self.items = [] if items is None else items
        self.expr = expr


# Yield (send to generator) expression
# @li (yield)
@dataclass(init=False)
class YieldExpr(Expr):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)


@dataclass(init=False)
class AwaitExpr(Expr):
    expr: Expr | None = None
    # True if a statement was transformed during type-checking stage
    # (to avoid setting up __await__ multiple times).
    transformed: bool = False

    def __init__(
        self,
        expr: Expr | None = None,
        transformed: bool = False,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.expr = expr
        self.transformed = transformed


@dataclass(init=False)
class AssignExpr(Expr):
    var: Expr | None = None
    expr: Expr | None = None

    def __init__(self, var: Expr | None = None, expr: Expr | None = None, **kwargs):
        super().__init__(**kwargs)
        self.var = var
        self.expr = expr


@dataclass(init=False)
class RangeExpr(Expr):
    start: Expr | None = None
    stop: Expr | None = None

    def __init__(self, start: Expr | None = None, stop: Expr | None = None, **kwargs):
        super().__init__(**kwargs)
        self.start = start
        self.stop = stop


@dataclass(init=False)
class StmtExpr(Expr):
    items: List[object]
    expr: Expr | None = None

    def __init__(
        self, items: List[object] | None = None, expr: Expr | None = None, **kwargs
    ):
        super().__init__(**kwargs)
        self.items = [] if items is None else items
        self.expr = expr


@dataclass(init=False)
class InstantiateExpr(Expr):
    expr: Expr | None = None
    items: List[Expr]

    def __init__(
        self, expr: Expr | None = None, items: List[Expr] | None = None, **kwargs
    ):
        super().__init__(**kwargs)
        self.items = [] if items is None else items
        self.expr = expr


@dataclass(init=False)
class Stmt(Node):
    # Flag that indicates if all types in a statement are inferred
    # (i.e. if a type-checking procedure was successful).
    done: bool = False

    def __init__(self, done: bool = False, **kwargs):
        super().__init__(**kwargs)
        self.done = done

    def first_in_block(self) -> Stmt | None:
        return self


@dataclass(init=False)
class SuiteStmt(Stmt):
    items: List[Stmt]

    def __init__(self, items: List[Stmt] | None = None, **kwargs):
        # C++ source: codon/parser/ast/stmt.cpp:35
        super().__init__(**kwargs)
        self.items = [] if items is None else items

    def first_in_block(self) -> Stmt | None:
        return None if not self.items else self.items[0].first_in_block()

    def flatten(self):
        flattened: List[Stmt] = []
        for item in self.items:
            if isinstance(item, SuiteStmt):
                flattened.extend(item.items)
            else:
                flattened.append(item)
        self.items = flattened

    def add(self, stmt: Stmt | None):
        if stmt is not None:
            self.items.append(stmt)
            self.done = self.done and stmt.done

    @staticmethod
    def wrap(stmt: Stmt | None) -> SuiteStmt | None:
        if stmt is None:
            return None
        return (
            stmt if isinstance(stmt, SuiteStmt) else SuiteStmt(items=[stmt], info=stmt)
        )


@dataclass(init=False)
class BreakStmt(Stmt):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)


@dataclass(init=False)
class ContinueStmt(Stmt):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)


@dataclass(init=False)
class ExprStmt(Stmt):
    expr: Expr | None = None

    def __init__(self, expr: Expr | None = None, **kwargs):
        super().__init__(**kwargs)
        self.expr = expr


@dataclass(init=False)
class AssignStmt(Stmt):
    class Mode(Enum):
        Assign = 0
        Update = 1
        UpdateAtomic = 2
        ThreadLocalAssign = 3

    lhs: Expr | None = None
    rhs: Expr | None = None
    type_expr: Expr | None = None
    update: AssignStmt.Mode = Mode.Assign

    def __init__(
        self,
        lhs: Expr | None = None,
        rhs: Expr | None = None,
        type_expr: Expr | None = None,
        update: AssignStmt.Mode = Mode.Assign,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.lhs = lhs
        self.rhs = rhs
        self.type_expr = type_expr
        self.update = update

    def is_assignment(self):
        return self.update is AssignStmt.Mode.Assign

    def is_update(self):
        return self.update is AssignStmt.Mode.Update

    def is_atomic_update(self):
        return self.update is AssignStmt.Mode.UpdateAtomic

    def is_thread_local(self):
        return self.update is AssignStmt.Mode.ThreadLocalAssign

    def set_update(self):
        self.update = AssignStmt.Mode.Update

    def set_atomic_update(self):
        self.update = AssignStmt.Mode.UpdateAtomic

    def set_thread_local(self):
        self.update = AssignStmt.Mode.ThreadLocalAssign


@dataclass(init=False)
class DelStmt(ExprStmt):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)


@dataclass(init=False)
class PrintStmt(Stmt):
    items: List[Expr]
    # True if there is a dangling comma after print: print a,
    no_newline: bool = False

    def __init__(
        self, items: List[Expr] | None = None, no_newline: bool = False, **kwargs
    ):
        super().__init__(**kwargs)
        self.items = [] if items is None else items
        self.no_newline = no_newline

    def has_newline(self):
        return not self.no_newline


@dataclass(init=False)
class ReturnStmt(ExprStmt):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)


@dataclass(init=False)
class YieldStmt(ExprStmt):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)


@dataclass(init=False)
class AssertStmt(Stmt):
    expr: Expr | None = None
    message: Expr | None = None

    def __init__(self, expr: Expr | None = None, message: Expr | None = None, **kwargs):
        super().__init__(**kwargs)
        self.expr = expr
        self.message = message


@dataclass(init=False)
class WhileStmt(Stmt):
    cond: Expr | None = None
    suite: SuiteStmt | None = None
    else_suite: SuiteStmt | None = None
    # Set if a while loop is used to emulate goto statement
    # (as `while gotoVar: ...`).
    goto_var: str = ""

    def __init__(
        self,
        cond: Expr | None = None,
        suite: SuiteStmt | None = None,
        else_suite: SuiteStmt | None = None,
        goto_var: str = "",
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.cond = cond
        self.suite = SuiteStmt.wrap(suite)
        self.else_suite = SuiteStmt.wrap(else_suite)
        self.goto_var = goto_var


@dataclass(init=False)
class ForStmt(Stmt):
    var: Expr | None = None
    iter: Expr | None = None
    suite: SuiteStmt | None = None
    else_suite: SuiteStmt | None = None
    decorator: Expr | None = None
    omp_args: List[CallExpr.Arg]
    async_: bool = False
    # Indicates if iter was wrapped with __iter__() call.
    wrapped: bool = False
    # True if there are no break/continue within the loop
    flat: bool = False

    def __init__(
        self,
        var: Expr | None = None,
        iter: Expr | None = None,
        suite: SuiteStmt | None = None,
        else_suite: SuiteStmt | None = None,
        decorator: Expr | None = None,
        omp_args: List[CallExpr.Arg] | None = None,
        async_: bool = False,
        wrapped: bool = False,
        flat: bool = False,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.var = var
        self.iter = iter
        self.suite = SuiteStmt.wrap(suite)
        self.else_suite = SuiteStmt.wrap(else_suite)
        self.decorator = decorator
        self.omp_args = [] if omp_args is None else omp_args
        self.async_ = async_
        self.wrapped = wrapped
        self.flat = flat


@dataclass(init=False)
class IfStmt(Stmt):
    cond: Expr | None = None
    if_suite: SuiteStmt | None = None
    else_suite: SuiteStmt | None = None

    def __init__(
        self,
        cond: Expr | None = None,
        if_suite: SuiteStmt | None = None,
        else_suite: SuiteStmt | None = None,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.cond = cond
        self.if_suite = SuiteStmt.wrap(if_suite)
        self.else_suite = SuiteStmt.wrap(else_suite)


@dataclass(init=False)
class MatchStmt(Stmt):
    @dataclass(init=False)
    class Case(Node):
        pattern: Expr | None = None
        guard: Expr | None = None
        suite: SuiteStmt | None = None

        def __init__(
            self,
            pattern: Expr | None = None,
            guard: Expr | None = None,
            suite: SuiteStmt | None = None,
        ):
            self.pattern = pattern
            self.guard = guard
            self.suite = SuiteStmt.wrap(suite)

    expr: Expr | None = None
    items: List[MatchStmt.Case]

    def __init__(
        self,
        expr: Expr | None = None,
        items: List[MatchStmt.Case] | None = None,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.items = [] if items is None else items
        self.expr = expr


@dataclass(init=False)
class ImportStmt(Stmt):
    """
    This node describes various kinds of import statements:
    - from from import what (as as)
    - import what (as as)
    - from c import what(args...) (-> ret) (as as)
    - from .(dots...)from import what (as as)
    """

    from_expr: Expr | None = None
    what: Expr | None = None
    # Function argument types for C imports.
    args: List[Param]
    # Function return type for C imports.
    ret: Expr | None = None
    as_: str = ""
    # Number of dots in a relative import (e.g. dots is 3 for "from ...foo").
    dots: int = 0
    # Set if this is a function C import (not variable import)
    is_function: bool = True

    def __init__(
        self,
        from_expr: Expr | None = None,
        what: Expr | None = None,
        args: List[Param] | None = None,
        ret: Expr | None = None,
        as_: str = "",
        dots: int = 0,
        is_function: bool = True,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.from_expr = from_expr
        self.what = what
        self.args = [] if args is None else args
        self.ret = ret
        self.as_ = as_
        self.dots = dots
        self.is_function = is_function

    def is_c_var(self):
        return not self.is_function


@dataclass(init=False)
class TryStmt(Stmt):
    @dataclass(init=False)
    class Except(Stmt):
        var: str = ""
        exc: Expr | None = None
        suite: SuiteStmt | None = None

        def __init__(
            self,
            var: str = "",
            exc: Expr | None = None,
            suite: SuiteStmt | None = None,
            **kwargs,
        ):
            super().__init__(**kwargs)
            self.var = var
            self.exc = exc
            self.suite = SuiteStmt.wrap(suite)

    suite: SuiteStmt | None = None
    items: List[TryStmt.Except]
    else_suite: SuiteStmt | None = None
    finally_suite: SuiteStmt | None = None

    def __init__(
        self,
        suite: SuiteStmt | None = None,
        items: List[TryStmt.Except] | None = None,
        else_suite: SuiteStmt | None = None,
        finally_suite: SuiteStmt | None = None,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.items = [] if items is None else items
        self.suite = SuiteStmt.wrap(suite)
        self.else_suite = SuiteStmt.wrap(else_suite)
        self.finally_suite = SuiteStmt.wrap(finally_suite)


@dataclass(init=False)
class ThrowStmt(Stmt):
    expr: Expr | None = None
    from_expr: Expr | None = None
    # True if a statement was transformed during type-checking stage
    # (to avoid setting up ExcHeader multiple times).
    transformed: bool = False

    def __init__(
        self,
        expr: Expr | None = None,
        from_expr: Expr | None = None,
        transformed: bool = False,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.expr = expr
        self.from_expr = from_expr
        self.transformed = transformed


@dataclass(init=False)
class GlobalStmt(Stmt):
    var: str = ""
    non_local: bool = False

    def __init__(self, var: str = "", non_local: bool = False, **kwargs):
        super().__init__(**kwargs)
        self.var = var
        self.non_local = non_local


@dataclass(init=False)
class FunctionStmt(Stmt):
    name: str = ""
    ret: Expr | None = None
    items: List[Param]
    suite: SuiteStmt | None = None
    decorators: List[Expr]
    async_: bool = False
    signature: str = ""

    def __init__(
        self,
        name: str = "",
        ret: Expr | None = None,
        items: List[Param] | None = None,
        suite: SuiteStmt | None = None,
        decorators: List[Expr] | None = None,
        async_: bool = False,
        signature: str = "",
        **kwargs,
    ):
        # C++ source: codon/parser/ast/stmt.cpp:570
        super().__init__(**kwargs)
        self.items = [] if items is None else items
        self.name = name
        self.ret = ret
        self.suite = SuiteStmt.wrap(suite)
        self.decorators = [] if decorators is None else decorators
        self.async_ = async_
        self.signature = signature

    def get_signature(self):
        """A function signature that consists of generics and arguments in a S-expression form."""
        if not self.signature:
            self.signature = ":".join(
                "-" if p.type is None else str(p.type) for p in self.items
            )
        return self.signature

    def get_star_arg(self) -> int:
        return next(
            (
                index
                for index, p in enumerate(self.items)
                if p.name.startswith("*") and not p.name.startswith("**")
            ),
            len(self.items),
        )

    def get_kwstar_arg(self) -> int:
        return next(
            (index for index, p in enumerate(self.items) if p.name.startswith("**")),
            len(self.items),
        )

    def get_docstr(self) -> str:
        return get_docstring(self.suite)

    # Check if a function can be called with the given arguments.
    # See @c reorderNamedArgs for details.
    def get_non_inferrable_generics(self) -> Set[str]:
        class IdMatch(Visitor):
            def __init__(self, value):
                self.value = value

            def visit_IdExpr(self, i):
                return i.value == self.value

        def contains_id(expr, name):
            return IdMatch(name).accept(expr)

        result: Set[str] = set()
        for i in self.items:
            if i.is_generic() and i.default_value is None:
                inferrable = False
                for candidate in self.items:
                    if candidate.type and contains_id(candidate.type, i.name):
                        inferrable = True
                        break
                if self.ret and contains_id(self.ret, i.name):
                    inferrable = True
                if not inferrable:
                    result.add(i.name)
        return result

    def has_function_attr(self, attribute: str):
        if a := self.get(Attr.FunctionAttributes):
            return attribute in a


@dataclass(init=False)
class ClassStmt(Stmt):
    name: str = ""
    items: List[Param]
    suite: SuiteStmt | None = None
    decorators: List[Expr]
    base_classes: List[Expr]

    def __init__(
        self,
        name: str = "",
        items: List[Param] | None = None,
        suite: SuiteStmt | None = None,
        decorators: List[Expr] | None = None,
        base_classes: List[Expr] | None = None,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.items = [] if items is None else items
        self.name = name
        self.suite = SuiteStmt.wrap(suite)
        self.decorators = [] if decorators is None else decorators
        self.base_classes = [] if base_classes is None else base_classes

    def is_record(self):
        return self.has(Attr.Tuple)

    def get_docstr(self) -> str:
        return get_docstring(self.suite)

    @staticmethod
    def is_class_var(param: Param):
        match param.type:
            case IndexExpr(expr=IdExpr("ClassVar")):
                return True
            case _:
                return False


@dataclass(init=False)
class YieldFromStmt(ExprStmt):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)


@dataclass(init=False)
class WithStmt(Stmt):
    items: List[Expr]
    vars: List[str]
    suite: SuiteStmt | None = None
    async_: bool = False

    def __init__(
        self,
        items: List[Expr] | None = None,
        vars: List[str] | None = None,
        suite: SuiteStmt | None = None,
        async_: bool = False,
        **kwargs,
    ):
        super().__init__(**kwargs)
        assert len(self.items) == len(self.vars), "vector size mismatch"
        self.items = [] if items is None else items
        self.vars = [] if vars is None else vars
        self.suite = SuiteStmt.wrap(suite)
        self.async_ = async_


@dataclass(init=False)
class CustomStmt(Stmt):
    keyword: str = ""
    expr: Expr | None = None
    suite: SuiteStmt | None = None

    def __init__(
        self,
        keyword: str = "",
        expr: Expr | None = None,
        suite: SuiteStmt | None = None,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.keyword = keyword
        self.expr = expr
        self.suite = SuiteStmt.wrap(suite)


@dataclass(init=False)
class DirectiveStmt(Stmt):
    key: str = ""
    value: str = ""

    def __init__(self, key: str = "", value: str = "", **kwargs):
        super().__init__(**kwargs)
        self.key = key
        self.value = value


@dataclass(init=False)
class AssignMemberStmt(Stmt):
    lhs: Expr | None = None
    member: str = ""
    rhs: Expr | None = None
    type_expr: Expr | None = None

    def __init__(
        self,
        lhs: Expr | None = None,
        member: str = "",
        rhs: Expr | None = None,
        type_expr: Expr | None = None,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.lhs = lhs
        self.member = member
        self.rhs = rhs
        self.type_expr = type_expr


@dataclass(init=False)
class CommentStmt(Stmt):
    comment: str = ""

    def __init__(self, comment: str = "", **kwargs):
        super().__init__(**kwargs)
        self.comment = comment


def get_static_generic(expr: Expr) -> object:
    match expr:
        case IndexExpr(expr=IdExpr(value="Static" | "Literal"), index=IdExpr(value=v)):
            return Literal.Kind.from_string(v)
        case _:
            return Literal.Kind.Runtime

def get_docstring(suite) -> str:
    match suite:
        case SuiteStmt(stmts=[ExprStmt(expr=StringExpr(value=v)), *_]):
            return v
        case _:
            return ""
