FROM quay.io/pypa/manylinux2014_aarch64

# - Codon needs ninja >= 1.10.
# - Codon needs Python 3 with shared libraries.
#   Since manylinux ships with static libraries, pyenv is used to build shared libraries.
# - Python needs OpenSSL >= 1.1.
# - The recent git security checks are disabled by marking everything "safe" until all dependencies get updated.
RUN yum -y update && \
    yum -y install gcc gcc-c++ gcc-gfortran make wget \
                   patch bzip2 readline-devel sqlite sqlite-devel \
                   bzip2-devel tk-devel libffi-devel xz-devel zlib-devel && \
    yum -y install https://linux.mellanox.com/public/repo/doca/2.2.0/centos7.6/aarch64/openssl11-devel-1.1.1k-5.el7.aarch64.rpm \
                   https://linux.mellanox.com/public/repo/doca/2.2.0/centos7.6/aarch64/openssl11-1.1.1k-5.el7.aarch64.rpm \
                   https://linux.mellanox.com/public/repo/doca/2.2.0/centos7.6/aarch64/openssl11-libs-1.1.1k-5.el7.aarch64.rpm && \
    yum -y install https://linux.mellanox.com/public/repo/doca/2.2.0/centos7.6/aarch64/ninja-build-1.10.2-3.el7.aarch64.rpm && \
    git clone https://github.com/pyenv/pyenv.git ~/.pyenv && \
    CPPFLAGS="-I/usr/include/openssl11" LDFLAGS="-L/usr/lib64/openssl11 -lssl -lcrypto" ~/.pyenv/bin/pyenv install -s 3.11 && \
    curl -L https://github.com/exaloop/llvm-project/releases/download/codon-20.1.7/llvm-codon-20.1.7-manylinux2014-aarch64.tar.bz2 | tar jxf - -C /opt && \
    echo -ne "[safe]\ndirectory = *" > /root/.gitconfig

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
